akvo/unep-gpml

backend/dev/src/dev.clj, backend/src/gpml/db/country-group.sql, backend/src/gpml/db/country_group.clj, backend/src/gpml/db/landing.clj, backend/src/gpml/db/landing.sql, backend/src/gpml/handler/landing.clj, backend/test/gpml/db/landing_test.clj
Also, adds a simple test for the landing page data
=> Switch landing page data to fetch real data

ci/k8s/deployment.yml.template
=> Added rolling strategy

backend/resources/gpml/config.edn, frontend/nginx/conf.d/default.conf
=> Added /healthz check

frontend/public/index.html
The `abstract` was copied from gpmarinelitter.org website
=> [#300] Update `description` and `abstract`

backend/resources/gpml/config.edn, frontend/package.json, frontend/src/index.js, frontend/src/utils/api.js, frontend/yarn.lock
Here is a sample Sentry issue generated by this [configuration](https://sentry.io/organizations/akvo-foundation/issues/2469453284/).
=> Configure Sentry in the front-end and report axios errors to Sentry

frontend/src/modules/initiative/schema.js
I've also removed the section and the part numbers, in separate commits. We can drop those commits, if they don't make sense.
=> Remove all numbering on the Initiative form

docker-compose.override.yml
=> [#311] Update pgAdmin4

frontend/src/modules/action-plan/form-schema.js, frontend/src/modules/financing-resource/form-schema.js, frontend/src/modules/policy/form-schema.js, frontend/src/modules/profile/preview.jsx, frontend/src/modules/technical-resource/form-schema.js, frontend/src/modules/technology/form-schema.js
=> Miscellaneous UI label/placeholder tweaks

backend/dev/src/gpml/seeder/main.clj, frontend/src/modules/details/view.jsx
- Fix the seeder code to correctly seed resources publish year
- Show links even when they don't have a name
=> Fix a couple of bugs causing missing data for resources

backend/src/gpml/handler/profile.clj
=> [#318] Remove debug `(prn ,,,)`

backend/src/gpml/db/browse.clj, backend/src/gpml/db/browse.sql, backend/src/gpml/handler/browse.clj, backend/test/gpml/handler/browse_test.clj, frontend/src/modules/browse/view.jsx, frontend/src/root.jsx, frontend/src/utils/misc.js
The PR intends to fix pagination and resource counts on the browse page. 
But, in the process, I caught a couple of other bugs which are also fixed in this PR.
=> Correct counts in browse page and couple of other bug fixes

db/script/set-admin.sh
=> [#342] Add script to define a local admin account

frontend/package.json, frontend/yarn.lock
Configure @babel/preset-env to transpile to older browsers
=> [#335] Adds babel/preset-env & update caniuse-lite

frontend/src/modules/details/view.jsx
- [#340] Prepend https:// on links when is not present
- [#340] Extract logic to helper function
=> 340 resource links

frontend/src/modules/policy/form-schema.js, frontend/src/utils/forms/form-file.js
I'm going to submit separate PRs for each form, so that we don't have one huge PR. 
Also, some additional options like "Not applicable" need to be added to some of the fields, but I plan to add them in a separate PR, since they are not fields that have newly been made mandatory.
- Add CSS to display image input as required field. 
- Add some mandatory fields to policy form
- Re-order policy form based on the original spreadsheet (linked in the issue): https://drive.google.com/file/d/1vGpCitycANlaBxB2i1yWvYIjh2QXPlSO/view
=> 243 policy form changes

frontend/src/modules/signup/signup-form.jsx
=> [#339] Correctly handle missing props in tags data on profile form

frontend/src/modules/action-plan/form.jsx, frontend/src/modules/financing-resource/form.jsx, frontend/src/modules/initiative/view.jsx, frontend/src/modules/policy/form.jsx, frontend/src/modules/technical-resource/form.jsx, frontend/src/modules/technology/form.jsx, frontend/src/utils/forms/index.js
- Clearing a required field should make the form not submittable
- When a form is submitted and edited immediately, the data is not fetched since the check for the API call was incorrect.
=> Edit UX fixes

frontend/src/modules/signup/view.jsx
=> [#378] Use screen_hint auth0 value to show sign-up view

backend/resources/migrations/078-invitation-table.down.sql, backend/resources/migrations/078-invitation-table.up.sql, backend/src/gpml/db/invitation.clj, backend/src/gpml/db/invitation.sql
@punchagan Finally added a couple of columns more (created and accepted) to track better the use/life of invitation entities
=> [#367] Add invitation [db] table and db.invitation [backend] ns

frontend/src/container.scss, frontend/src/main.scss, frontend/src/modules/profile/admin.jsx, frontend/src/modules/profile/review.jsx, frontend/src/modules/profile/stakeholders.jsx, frontend/src/modules/profile/styles.scss, frontend/src/modules/profile/view.jsx, frontend/src/modules/signup/styles.scss, frontend/src/utils/misc.js
=> 369 fe profile admin page style

frontend/src/modules/glossary/glossary.jsx, frontend/src/modules/glossary/styles.scss, frontend/src/root.jsx
=> 365 fe glossary page

backend/resources/migrations/084-create-organisation-tag-table.down.sql, backend/resources/migrations/084-create-organisation-tag-table.up.sql, backend/src/gpml/db/organisation.sql
Relates [#367]
- to store entity services
- also adding minimal CRUDdb functionality
=> [#367] Add organisation tags db relation

frontend/src/modules/glossary/glossary.jsx, frontend/src/modules/glossary/styles.scss
=> [#365] Update glossary content based on doc text

backend/src/gpml/handler/stakeholder.clj, backend/test/gpml/handler/stakeholder_test.clj, frontend/src/modules/signup/view.jsx
=> [#367] Adapt to pullstate pattern

frontend/src/modules/about/about-us.jsx
Update to clean seas link
Update the pdf's links
Update to signu up link text and url
=> [#410] Update to about us

frontend/src/modules/browse/map-landing.jsx, frontend/src/modules/browse/maps.jsx, frontend/src/modules/browse/view.jsx
=> 372 fe resource overview page

frontend/src/modules/signup-old/view-style.scss, frontend/src/modules/signup-old/view.jsx
=> [#367] Improve signup choice view style

frontend/src/modules/signup/entitySchema.js, frontend/src/modules/signup/entityUiSchema.json, frontend/src/modules/signup/form.jsx, frontend/src/modules/signup/stakeholderSchema.js, frontend/src/modules/signup/stakeholderUiSchema.json, frontend/src/root.jsx, frontend/src/utils/forms/form-text-icon.js, frontend/src/utils/profile.js
Also included:
- Individual Form: Title and Last Name should be separate rows
- Fix linkedIn key
=> [#367] Reload profile after submitting

frontend/src/modules/landing/new-home.jsx, frontend/src/modules/landing/new-styles.scss
This PR supersedes changes on #423 for event related changes on the home page. #423 is quite difficult to merge with the rebase situation...
=> Event related fixes for home page

frontend/src/container.scss, frontend/src/footer.jsx, frontend/src/main.scss, frontend/src/modules/browse/styles.scss, frontend/src/modules/dropdown-menu/about.jsx, frontend/src/modules/dropdown-menu/responsive-menu.jsx, frontend/src/modules/landing/new-home.jsx, frontend/src/modules/landing/new-styles.scss, frontend/src/modules/topics/styles.scss, frontend/src/modules/topics/topic.jsx, frontend/src/root.jsx, frontend/src/utils/chart/index.js
=> 361 fe homepage feedback

frontend/src/container.scss, frontend/src/modules/browse/styles.scss, frontend/src/modules/browse/view.jsx, frontend/src/modules/landing/new-home.jsx, frontend/src/modules/landing/new-styles.scss, frontend/src/root.jsx
=> [#361] Home page feedback

frontend/src/modules/signup-old/view.jsx, frontend/src/modules/signup/entitySchema.js, frontend/src/modules/signup/entityUiSchema.json, frontend/src/modules/signup/form.jsx, frontend/src/modules/signup/stakeholderSchema.js, frontend/src/root.jsx, frontend/src/utils/forms/form-text-icon.js, frontend/src/utils/profile.js
and a couple of minor things/commits included
=> [#367] Once logged in the form allow user go back to the homepage

frontend/src/modules/initiative/styles.scss, frontend/src/modules/signup-old/view-style.scss, frontend/src/modules/signup-old/view.jsx, frontend/src/modules/signup/styles.scss, frontend/src/modules/signup/view.jsx
=> 367 fe signup form improvement

frontend/src/modules/signup/entitySchema.js, frontend/src/modules/signup/entityUiSchema.json, frontend/src/modules/signup/stakeholderSchema.js, frontend/src/modules/signup/stakeholderUiSchema.json, frontend/src/modules/signup/styles.scss, frontend/src/modules/signup/view.jsx, frontend/src/utils/forms/form-checkbox.js, frontend/src/utils/forms/form-checkboxes.js, frontend/src/utils/forms/form-textarea.js, frontend/src/utils/forms/index.js
=> 367 fe signup stakeholder/entity signup view

backend/resources/gpml/config.edn, backend/src/gpml/handler/landing.clj, backend/src/gpml/handler/nav.clj, frontend/src/modules/browse/map-landing.jsx, frontend/src/modules/landing/new-home.jsx, frontend/src/root.jsx
- Don't fetch map data until the map is being loaded
- Don't show a loading spinner for the whole page, when loading the events data for home page.
=> Make home page appear to load faster

backend/resources/gpml/config.edn, backend/resources/migrations/086-add-stakeholder-public-database.down.sql, backend/resources/migrations/086-add-stakeholder-public-database.up.sql, backend/resources/migrations/087-add-stakeholder-company-name.down.sql, backend/resources/migrations/087-add-stakeholder-company-name.up.sql, backend/src/gpml/db.clj, backend/src/gpml/db/stakeholder.sql, backend/src/gpml/handler/stakeholder.clj, backend/test/gpml/handler/detail_test.clj, backend/test/gpml/handler/organisation_test.clj, backend/test/gpml/handler/profile_test.clj, frontend/src/modules/signup/entitySchema.js, frontend/src/modules/signup/entityUiSchema.json, frontend/src/modules/signup/stakeholderSchema.js, frontend/src/modules/signup/stakeholderUiSchema.json
=> Signup  stakeholder fields

frontend/src/footer.jsx, frontend/src/main.scss, frontend/src/modules/dropdown-menu/about.jsx, frontend/src/modules/dropdown-menu/data-hub.jsx, frontend/src/modules/dropdown-menu/responsive-menu.jsx, frontend/src/modules/landing/new-home.jsx
=> [#361] Homepage & Nav improvement

frontend/src/main.scss, frontend/src/modules/signup/entitySchema.js, frontend/src/modules/signup/entityUiSchema.json, frontend/src/modules/signup/stakeholder.js, frontend/src/modules/signup/stakeholderSchema.js, frontend/src/modules/signup/stakeholderUiSchema.json, frontend/src/modules/signup/styles.scss, frontend/src/modules/signup/view.jsx, frontend/src/utils/forms/form-checkbox.js, frontend/src/utils/forms/form-textarea.js, frontend/src/utils/geo.js
=> [#367] Sign up individual/entity form improvement 

frontend/src/container.scss, frontend/src/modules/browse/map-landing.jsx, frontend/src/modules/browse/maps.jsx
=> 372 fe map view on mobile

backend/resources/migrations/088-add-organisation-representative-group-details.down.sql, backend/resources/migrations/088-add-organisation-representative-group-details.up.sql, backend/src/gpml/db/organisation.sql, backend/src/gpml/handler/stakeholder.clj, frontend/src/modules/signup/entity.js, frontend/src/modules/signup/entitySchema.js, frontend/src/modules/signup/entityUiSchema.json, frontend/src/modules/signup/form.jsx, frontend/src/modules/signup/view.jsx, frontend/src/store.js
=> 367 Signup entity form improvement (FE)

frontend/src/modules/signup/view.jsx
- Forms: submenu should stay in focus when scrolling [link to feedback](https://docs.google.com/spreadsheets/d/10y4U-AYdkCflxN9rWAB4fuEblDP71eAhQwR-kFvkYhI/edit?pli=1#gid=210015698&range=105:105)
=> [#367] Make form submenu stay focus when scroll

frontend/src/footer.jsx, frontend/src/main.scss
=> 361 Small updates for homepage

frontend/src/modules/dropdown-menu/connect-stakeholders.jsx, frontend/src/root.jsx
=> 361 fe nav header update

frontend/src/main.scss, frontend/src/modules/signup/entitySchema.js, frontend/src/modules/signup/form.jsx, frontend/src/modules/signup/stakeholderSchema.js, frontend/src/modules/signup/view.jsx
- i) country; ii) an affiliation needs to be provided, otherwise there needs to be an option to select they are private citizens and they don't have an affiliation
- MO: there should be a submit button at the bottom on the last page.
- What services/ expertise does your organisation offer? > MO: Heidi suggested to update the question to: "What areas of interest or expertise does your entity have or offer?"
=> 367 fe signup form small updates

frontend/src/modules/landing/new-home-static-content.js, frontend/src/modules/landing/new-home.jsx
- https://docs.google.com/spreadsheets/d/10y4U-AYdkCflxN9rWAB4fuEblDP71eAhQwR-kFvkYhI/edit?pli=1#gid=966469174&range=10:10
- https://docs.google.com/spreadsheets/d/10y4U-AYdkCflxN9rWAB4fuEblDP71eAhQwR-kFvkYhI/edit?pli=1#gid=966469174&range=12:12
=> [#361] Our community section: update profile id

frontend/src/footer.jsx, frontend/src/main.scss, frontend/src/modules/browse/view.jsx, frontend/src/modules/dropdown-menu/connect-stakeholders.jsx, frontend/src/modules/dropdown-menu/data-hub.jsx, frontend/src/modules/dropdown-menu/knowledge-exchange.jsx, frontend/src/modules/dropdown-menu/responsive-menu.jsx, frontend/src/modules/stakeholders/view.jsx, frontend/src/root.jsx
=> 361 fe submenu nav not refresh

frontend/src/modules/browse/view.jsx
=> [#361] Add search disclaimer text

frontend/src/modules/signup/form.jsx, frontend/src/modules/signup/stakeholder.js, frontend/src/modules/signup/stakeholderSchema.js, frontend/src/modules/signup/stakeholderUiSchema.json
=> 367 Individual form: Adding private citizen on affiliation section

frontend/src/modules/landing/new-home.jsx, frontend/src/modules/landing/new-styles.scss
The detail feedback is [here](https://docs.google.com/spreadsheets/d/10y4U-AYdkCflxN9rWAB4fuEblDP71eAhQwR-kFvkYhI/edit?pli=1#gid=966469174&range=14:14)
=> 361 fe event content

frontend/src/modules/browse/maps.jsx, frontend/src/modules/browse/view.jsx, frontend/src/modules/details/view.jsx
=> 479 fe api call bug

frontend/src/modules/initiative/form.jsx, frontend/src/modules/signup/form.jsx, frontend/src/modules/signup/stakeholder.js, frontend/src/modules/signup/stakeholderSchema.js, frontend/src/modules/signup/stakeholderUiSchema.json, frontend/src/utils/forms/form-select.js, frontend/src/utils/forms/index.js, frontend/src/utils/forms/object-template.js
Note: non-member "other" option POST will be on separated PR
=> 485 fe members non members

frontend/src/modules/dropdown-menu/responsive-menu.jsx, frontend/src/modules/landing/new-home-static-content.js, frontend/src/modules/landing/new-home.jsx, frontend/src/modules/landing/new-styles.scss, frontend/src/utils/chart/TreeMap.js
=> 361 fe popular topic content

frontend/src/modules/browse/map-landing.jsx, frontend/src/modules/browse/map-styles.scss, frontend/src/modules/browse/maps.jsx, frontend/src/root.jsx, frontend/src/store.js
=> [#372] Multi-country/transnational list filter

frontend/src/modules/details/view.jsx
=> [#479] Remove `profile` from `isLoaded` flag

backend/resources/gpml/config.edn, backend/src/gpml/db/organisation.sql, backend/src/gpml/handler/organisation.clj, frontend/src/modules/details/view.jsx, frontend/src/modules/entity/form-schema.js, frontend/src/modules/entity/form.jsx, frontend/src/modules/entity/styles.scss, frontend/src/modules/entity/view.jsx, frontend/src/root.jsx, frontend/src/store.js, frontend/src/utils/forms/index.js
- if the payload fits well to BE, the work left is to check and change the `api.put` endpoint to the right path.
=> 554 fe entity form

frontend/src/modules/signup/entitySchema.js, frontend/src/modules/signup/form.jsx, frontend/src/modules/signup/view.jsx
- Set URL format to entity schema & setup error notification for validation
=> [#553] Fix Entity details URL validation

backend/resources/gpml/config.edn
=> [#489] Allow normal users (not admins) create events

frontend/src/modules/dropdown-menu/connect-stakeholders.jsx
Added Communities link pointing to discourse
=> [#570] Added Communities link

backend/src/gpml/db.clj, backend/src/gpml/db/review.sql, backend/src/gpml/handler/review.clj
This PR returns a new review.field `picture` that can be null or contains a full url
=> [#478] Include picture for each review in GET api/review?<query-args>

frontend/src/modules/entity/form-schema.js, frontend/src/modules/entity/form.jsx
This pull request contains fix of not showing geo coverage countries when transnational selected
=> [#561] Fix: Entity edit form transnational value

backend/resources/migrations/108-update-v-organisation.down.sql, backend/resources/migrations/108-update-v-organisation.up.sql, backend/src/gpml/db/organisation.sql, backend/src/gpml/handler/organisation.clj
=> [#561] Fix BE organisation

backend/src/gpml/auth.clj, backend/src/gpml/handler/auth.clj, backend/src/gpml/handler/resource.clj, backend/test/gpml/handler/resource_test.clj
relates #607 
most of the changes related with refactor and tidy up
=> [#607] BE Store resource owners

backend/dev/resources/examples/submission-initiative.json, backend/resources/migrations/111-add-url-to-topics.down.sql, backend/resources/migrations/111-add-url-to-topics.up.sql, backend/src/gpml/db/event.sql, backend/src/gpml/db/resource.sql, backend/src/gpml/handler/event.clj, backend/src/gpml/handler/initiative.clj, backend/src/gpml/handler/resource.clj, backend/test/gpml/handler/event_test.clj, backend/test/gpml/handler/initiative_test.clj, backend/test/gpml/handler/resource_test.clj
Add url db column to event, resource and initiative
=> Flexible forms be

frontend/src/modules/capacity-building/Banner.jsx, frontend/src/modules/capacity-building/json/slider.json, frontend/src/modules/capacity-building/styles.scss, frontend/src/modules/capacity-building/view.jsx, frontend/src/modules/case-studies/styles.scss, frontend/src/modules/case-studies/view.jsx, frontend/src/modules/left-sidebar/styles.scss
Most of these full images are landscape, and we show them in portrait. And we need to fix the thumbnail that looks "squeezed" by cropping the image
=> [#610] Fix: image thumbnails and slider

backend/resources/gpml/config.edn, backend/src/gpml/db/event.sql, backend/src/gpml/db/initiative.sql, backend/src/gpml/db/policy.sql, backend/src/gpml/db/resource.sql, backend/src/gpml/db/technology.sql, backend/src/gpml/handler/detail.clj, backend/src/gpml/handler/list.clj, backend/src/gpml/handler/policy.clj, backend/src/gpml/handler/resource.clj
- Resource details with stakeholder connections
- GET endpoint for listing resources
=> 625 resource detail be

frontend/src/modules/capacity-building/Banner.jsx, frontend/src/modules/capacity-building/json/capacity-building.json, frontend/src/modules/capacity-building/json/slider.json, frontend/src/modules/capacity-building/view.jsx, frontend/src/modules/case-studies/CaseStudy.jsx, frontend/src/modules/case-studies/styles.scss, frontend/src/modules/left-sidebar/LeftSidebar.jsx, frontend/src/modules/left-sidebar/styles.scss
=> [#610] Fix styling card and slides capacity building

frontend/src/modules/case-studies/CaseStudy.jsx, frontend/src/modules/case-studies/json/case-studies.json, frontend/src/modules/case-studies/json/stakeholders.json, frontend/src/modules/case-studies/styles.scss, frontend/src/modules/case-studies/view.jsx, frontend/src/modules/left-sidebar/styles.scss
=> [#612] Fix data case studies

backend/src/gpml/db/topic.clj, backend/src/gpml/handler/browse.clj, backend/test/gpml/handler/browse_test.clj
* Add time filters for event topics.
* Fix issue when `topic` param is empty.
=> 651 resource overview be

backend/src/gpml/db/community.clj, backend/src/gpml/handler/community.clj
* To avoid misunderstanding with FE.
=> [#699] Change offset to page

backend/src/gpml/db/topic.clj, backend/src/gpml/db/topic.sql, backend/src/gpml/handler/browse.clj, backend/test/gpml/db/topic_test.clj, backend/test/gpml/handler/browse_test.clj
* Performance improvements to the `browse` API.
=> 843 loading times

backend/src/gpml/db/topic.clj, backend/src/gpml/handler/browse.clj
=> [#849] Add sub-content-type filter to browse API

backend/src/gpml/db/detail.sql, backend/src/gpml/handler/detail.clj
* Separate entities from topics.
=> 857 details api refactor

backend/resources/migrations/135-update-stakeholder-affiliation-constraint.down.sql, backend/resources/migrations/135-update-stakeholder-affiliation-constraint.up.sql
=> [#860] Add ON DELETE SET NULL to stakeholder affiliation fkey

frontend/src/modules/knowledge-library/map-landing.jsx, frontend/src/modules/map/Map.jsx, frontend/src/modules/map/VerticalLegend.jsx, frontend/src/modules/map/config.js, frontend/src/modules/map/map-styles.scss
=> [#651] Add useVerticalLegend prop at Map component

backend/src/gpml/db/landing.clj, backend/src/gpml/db/landing.sql, backend/src/gpml/handler/landing.clj
* Also refactored the landing API a bit because there was a mistake:
- Stakeholder was not considering country groups
=> [#955] Return entity counts by country group

backend/src/gpml/db/tag.clj, backend/src/gpml/db/tag.sql, backend/src/gpml/handler/tag.clj
=> [#1019] Add tag filter for popular tags

backend/resources/gpml/config.edn, backend/src/gpml/db/stakeholder_association.sql, backend/src/gpml/handler/comment.clj
* Fix stakeholder-resource-association retrieval.
* Fix not to send notifications when the author is the resource owner.
* Fix UUID type specification in the swagger docs.
* Add swagger documentation for responses.
=> 1073 comments feature be

backend/resources/gpml/config.edn, backend/src/gpml/handler/comment.clj, backend/test/gpml/handler/comment_test.clj
* Fix comments API response schemas
=> 1073 Fix comments API response schemas

backend/resources/gpml/config.edn, backend/resources/migrations/144-alter-comment-table-title-drop-not-null-constraint.down.sql, backend/resources/migrations/144-alter-comment-table-title-drop-not-null-constraint.up.sql, backend/src/gpml/db/comment.sql, backend/src/gpml/handler/comment.clj, backend/test/gpml/handler/comment_test.clj
* Reply comments don't have a title.
=> 1073 Make comment `title` optional

backend/resources/gpml/config.edn, backend/src/gpml/auth.clj, backend/src/gpml/handler/organisation.clj
* Restrict PUT endpoint for organisation to admins and owners.
* PUT endpoint parameters should be optional
=> 1151 restrict update org to admin owner

backend/src/gpml/handler/stakeholder.clj
* We were not updating the organisation's owner, who created it.
=> [#1156] Fix entity creation not having an owner

backend/src/gpml/db/technology.sql
* As title does not exist in the technology table
Closes #1161
=> [#1161] Fix technology query replace title for name

backend/resources/gpml/config.edn, backend/src/gpml/db/resource/list.clj, backend/src/gpml/db/resource/list.sql, backend/src/gpml/handler/list.clj
* With additional filter `q` and response `limit` (defaults to 100).
=> [#1163] Change list API to return all resources from the platform

backend/src/gpml/db/resource/list.clj, backend/src/gpml/db/resource/list.sql, backend/src/gpml/handler/list.clj
See #1171 for details
Closes #1171
=> Change list API text search strategy

backend/resources/gpml/config.edn
=> [#1185] Make organisation content and member endpoints public

frontend/src/modules/stakeholder-overview/card.jsx, frontend/src/modules/stakeholder-overview/styles.scss
=> [#699] Display multiple tags on suggested profile card

backend/resources/migrations/148-add-stakeholder-tag-relation-category.down.sql, backend/resources/migrations/148-add-stakeholder-tag-relation-category.up.sql, backend/src/gpml/db/resource/tag.sql, backend/src/gpml/handler/resource/tag.clj
=> 1197 refactor stakeholder tags to add synthetic tag category

backend/src/gpml/db/community.clj, backend/src/gpml/handler/community.clj
=> [#1221] Add isMember filter to community API

backend/resources/migrations/151-fix-organisation-types-naming.down.sql, backend/resources/migrations/151-fix-organisation-types-naming.up.sql
=> [#1226] Replace organisations representative group types

backend/resources/migrations/154-add-related-content-table-and-functions.up.sql, backend/src/gpml/constants.clj, backend/src/gpml/db/event.sql, backend/src/gpml/db/initiative.sql, backend/src/gpml/db/policy.sql, backend/src/gpml/db/resource.sql, backend/src/gpml/db/resource/connection.clj, backend/src/gpml/db/resource/connection.sql, backend/src/gpml/db/resource/list.clj, backend/src/gpml/db/resource/list.sql, backend/src/gpml/db/resource/related_content.clj, backend/src/gpml/db/resource/related_content.sql, backend/src/gpml/db/technology.sql, backend/src/gpml/db/topic.clj, backend/src/gpml/handler/browse.clj, backend/src/gpml/handler/detail.clj, backend/src/gpml/handler/event.clj, backend/src/gpml/handler/initiative.clj, backend/src/gpml/handler/list.clj, backend/src/gpml/handler/policy.clj, backend/src/gpml/handler/resource.clj, backend/src/gpml/handler/resource/related_content.clj, backend/src/gpml/handler/technology.clj, backend/test/gpml/handler/technology_test.clj, frontend/src/modules/flexible-forms/form.jsx, frontend/src/modules/flexible-forms/view.jsx, frontend/src/utils/forms/form-autocomplete.js, frontend/src/utils/forms/form-select-search.js
* Refactor related_content to be a generic table.
=> 1271 refactor related content

backend/src/gpml/db/topic.sql
* Related resource is now a different table and not a column.
=> Fix resources export

backend/src/gpml/db/detail.sql, backend/src/gpml/db/landing.sql, backend/src/gpml/db/topic.clj, backend/src/gpml/db/topic.sql, backend/src/gpml/handler/browse.clj, backend/src/gpml/handler/detail.clj, backend/src/gpml/handler/landing.clj, backend/test/gpml/db/topic_test.clj, backend/test/gpml/handler/browse_test.clj, backend/test/gpml/handler/detail_test.clj
* Remove unnecessary data retrieval.
* Simplify the query using aggregations instead of subqueries.
=> Refactor topic query to simpler and with better performance

auth0/actions/login/inject-custom-claims.js
* This action is used in the post login process to inject a custom
role claim in the JWT IdToken of the user.
=> [#1299] Add Auth0 Action code for inject-custom-claims action

backend/src/gpml/db/submission.sql
* We were missing the `only` tags conditional in the aggregation CTEs.
* Closes #1306
=> [#1306] Fix tag submission count query

backend/dev/src/dev.clj, backend/project.clj, backend/src/gpml/db/action.clj, backend/src/gpml/db/action_detail.clj, backend/src/gpml/db/activity.clj, backend/src/gpml/db/archive.clj, backend/src/gpml/db/comment.clj, backend/src/gpml/db/community.clj, backend/src/gpml/db/country.clj, backend/src/gpml/db/country_group.clj, backend/src/gpml/db/currency.clj, backend/src/gpml/db/detail.clj, backend/src/gpml/db/event.clj, backend/src/gpml/db/favorite.clj, backend/src/gpml/db/initiative.clj, backend/src/gpml/db/invitation.clj, backend/src/gpml/db/landing.clj, backend/src/gpml/db/language.clj, backend/src/gpml/db/organisation.clj, backend/src/gpml/db/organisation_detail.clj, backend/src/gpml/db/policy.clj, backend/src/gpml/db/resource/list.clj, backend/src/gpml/db/review.clj, backend/src/gpml/db/stakeholder.clj, backend/src/gpml/db/stakeholder_association.clj, backend/src/gpml/db/submission.clj, backend/src/gpml/db/tag.clj, backend/src/gpml/db/technology.clj, backend/src/gpml/db/topic.clj, backend/src/gpml/db/topic_stakeholder_auth.clj
=> [#1308] Add ns-tracker to track and refresh HugSQL dependent files

backend/resources/migrations/155-add-thumbnail-property-to-resource-and-policy.up.sql, backend/src/gpml/handler/detail.clj, backend/src/gpml/handler/event.clj, backend/src/gpml/handler/initiative.clj, backend/src/gpml/handler/policy.clj, backend/src/gpml/handler/resource.clj, backend/src/gpml/handler/resource/related_content.clj, backend/src/gpml/handler/technology.clj, backend/src/gpml/util.clj
=> [#1297] Add thumbnail property to resource and policy

ci/k8s/deployment.template.yml
=> [#1311] Increase liveness and readiness probe delay for be container

backend/src/gpml/handler/event.clj
=> [#1315] Fix event post endpoint image property

backend/src/gpml/handler/detail.clj
=> [#1321] Add affiliation details to stakeholder in detail API

backend/src/gpml/db/favorite.clj, backend/src/gpml/db/favorite.sql
* We shouldn't do this type of statement generation. We should always
rely on parameter value list for this.
=> Fix delete-association DB function

backend/src/gpml/handler/resource/related_content.clj
* Sort those with thumbnail first, with image second and nils last.
=> [#1297] Sort related resources (content)

backend/resources/gpml/config.edn, backend/src/gpml/handler/organisation.clj
* Return 409 conflict HTTP status code if the organisation name
already exists.
* Log the error.
=> Improve organisation POST endpoint error handling

backend/resources/gpml/config.edn, backend/src/gpml/handler/detail.clj
=> [#1318] Fix resource deletion in the detail API

backend/src/gpml/db/stakeholder.sql, backend/src/gpml/handler/stakeholder/expert.clj
* Add expert count by country.
* Add affiliation details to the query result.
* Closes #1360
=> 1360 Add expert count by country and affiliation details

backend/resources/gpml/config.edn, backend/src/gpml/db/resource/geo_coverage.clj, backend/src/gpml/db/resource/geo_coverage.sql, backend/src/gpml/handler/stakeholder.clj, backend/src/gpml/handler/stakeholder/expert.clj, backend/src/gpml/handler/stakeholder/tag.clj, backend/src/gpml/handler/submission.clj
* Also refactored a bit the submission details because when reading
list the submission details, it was missing the affiliation details
too.
* Moved stakeholder tag specific functions to
gpml.handler.stakeholder.tag namespace.
* Make Stakeholder PUT endpoints more robust and improve error handling.
* Closes #1365
=> [#1365] Refactor stakeholder API update to check for opt data

backend/resources/gpml/config.edn, backend/src/gpml/db/stakeholder.sql, backend/src/gpml/domain/stakeholder.clj, backend/src/gpml/handler/review.clj, backend/test/gpml/handler/review_test.clj
* Add filters to get-reviewers.
* Add domain model for stakeholder as we needed to derive
information from the model.
* Refactor error handling.
* Refactor key names to use fully qualified namespace keywords (not
the shorthand version).
* Make namespace only functions private (they are only used in the same namespace they are defined)
* See #1368
=> [#1368] Refactor review handler and add filters to get-reviewers

backend/src/gpml/handler/stakeholder/tag.clj
* The previous diff was wrong because it wasn't taking into
consideration the different tags categories. In this new
implementation we are doing the diff per stakeholder tag category and
then merging all together into the canonical structrure. This way
we'll also have a consistent diff of update and create operations.
=> Fix stakeholder tags update/create

backend/resources/gpml/config.edn, backend/src/gpml/handler/stakeholder/expert.clj
=> [#1385] Add suggest expert API endpoint

backend/resources/migrations/162-add-delete-on-cascade-foreign-key-constraints-to-tags.up.sql
* Basically add ON DELETE CASCADE.
=> Improve tag mxn tables constraints

backend/src/gpml/db/topic.clj
[Closes #1404]
The counting logic was modified for ignoring duplicate tags, but it has not
working well, since all the resources were counted for each popular topic
(tag). Now we have fixed that part of the DB query to do the right counting,
ignoring duplicate tags until the root problem is fixed.
=> Fix popular topcis counting of Browse API GET endpoint #1404

backend/.clj-kondo/config.edn, backend/resources/gpml/config.edn, backend/resources/migrations/170-setup-project-schema.up.sql, backend/src/gpml/db/policy.clj, backend/src/gpml/db/project.clj, backend/src/gpml/db/project.sql, backend/src/gpml/db/project/geo_coverage.clj, backend/src/gpml/db/project/geo_coverage.sql, backend/src/gpml/db/tag.clj, backend/src/gpml/domain/project.clj, backend/src/gpml/domain/stakeholder.clj, backend/src/gpml/domain/types.clj, backend/src/gpml/handler/comment.clj, backend/src/gpml/handler/organisation_detail.clj, backend/src/gpml/handler/project.clj, backend/src/gpml/handler/responses.clj, backend/src/gpml/handler/stakeholder.clj, backend/src/gpml/handler/stakeholder/expert.clj, backend/src/gpml/handler/stakeholder_association.clj, backend/src/gpml/handler/util.clj, backend/src/gpml/util.clj, backend/test/gpml/handler/project_test.clj
Main:
* BE logic to manage projects.
* API and DB layer.
* Domain layer for project and schema specification.
Secondary solved issues:
* Fix update-if-not-exists util function. It wasn't checking if the
key existed or not.
* Added update-if-not-nil function.
* Remove old project entity DB functions and deprecate referenced
functions (they will removed in the
futured once PR #1437 is merged. It's currently waiting FE changes to
do so).
* See #1439
* Closes #1439
=> [#1439] Implement project API and db model

backend/src/gpml/handler/project.clj
* We were trying to insert geo coverage connections even though there
weren't none.
=> Fix project POST: don't create geo coverage if there isn't any

backend/resources/migrations/174-alter-table-project-add-stage-column.up.sql, backend/src/gpml/db/project.clj, backend/src/gpml/db/project.sql, backend/src/gpml/domain/project.clj, backend/src/gpml/handler/main.clj, backend/src/gpml/handler/project.clj, backend/test/gpml/handler/project_test.clj
Main issues:
* Updated DB model, API and Domain.
Secondary issues:
* Added a custom response body for validation and coercion errors.
* See #1462 
* Closes #1462
=> [#1462] Add project stage property

backend/resources/migrations/176-update-action-plan-sub-content-type.up.sql
* Action plan sub-content-type changed and so we have to update Database records using the old versions.
=> Fix action plan sub-content-type

backend/src/gpml/handler/image.clj
[closes #1492]
Some avatar repositories need user-agent to be provided as part of the request and we were missing that from BE. Now we inject it in the request as we fetch it from the user's browser.
Documented the code a bit to explain the image handling flow depending on each case, as it's a bit tricky.
=> Fix img download by providing user-agent to req

backend/src/gpml/handler/stakeholder.clj
[closes #1502]
Right now we are sending email notifications when a new stakelholder is registered, before the whole process has ended ok. So, for example, tags creation related to the new stakeholder happens after the email notification is sent.
However, we need to be sure all the steps related to the stakeholder registration have been performed ok before sending the email notification, which should be always the last step during the registration process.
So for doing the above, we have moved the notif. email sending place as last step, rather than doing it when creating the stakeholder entity. Besides, we do it once any possible exception has been thrown, so there is no need for extra checks at this point.
=> Send email notif. in stakeh. reg. as last step

backend/src/gpml/handler/stakeholder.clj
* Add `affiliation` parameter to convert from non-private citizen to private one.
* Define `gpml.handler.stakeholder` namespace integrate keys explicitly.
=> Fix stakeholder update endpoint

ci/k8s/deployment.template.yml
=> [#1517] Add CONTACT_COBSEA_MANAGEMENT_EMAIL env var

backend/resources/migrations/182-add-case-study-url-property.up.sql, backend/src/gpml/domain/case_study.clj
=> [#1526] Add case-study url property

backend/resources/gpml/config.edn, backend/resources/migrations/183-update-case-study-schema.up.sql, backend/src/gpml/db/case_study.clj, backend/src/gpml/db/country_group.clj, backend/src/gpml/db/country_group.sql, backend/src/gpml/domain/case_study.clj, backend/src/gpml/domain/geo_coverage.clj, backend/src/gpml/handler/programmatic/case_study.clj
=> [#1528] Add endpoint to import case studies from static file

backend/src/gpml/db/topic.clj, backend/src/gpml/handler/browse.clj
=> Fix order by set NULLs last

backend/src/gpml/service/file.clj
[Re #1543]
Removed forgotten print statement that shouldn't be there.
=> 1543 Remove forgotten print

backend/src/gpml/handler/stakeholder.clj
[Re #1578]
Improved the response of this API endpoint to always return an empty vector as value of `suggested-profiles` key, instead of returning a collection of empty maps, which was kind of cumbersome to deal with for the frontend. For this we have made the `get-stakeholder-profile` related function to return `nil` instead of an empty map, when no profile has been found, so we can filter out those results from the collection of suggested profiles. In this case, we have kept the original response of an empty map in the expected
(single-profile) use-cases.
On the other hand, we were wrongly using `get-stakeholder-profile` function, passing wrong arguments to this function within this endpoint's handler. So now we have fixed that and we get the expected results as well.
=> 1578 Fix and improve `/api/profile/suggested` GET API

backend/resources/gpml/config.edn, backend/src/gpml/db/organisation.sql, backend/src/gpml/handler/organisation.clj, backend/src/gpml/service/stakeholder.clj
All the details are explained in the #1580 issue.
Besides there are additional details of the expected usage of this endpoint in the related  backend-side [task](https://app.asana.com/0/1204455129773834/1205394076911787/f).
=> 1580 implement org request membership endpoint

frontend/src/components/button.jsx, frontend/src/components/cat-tag-select/cat-tag-select.jsx, frontend/src/components/form-label.jsx, frontend/src/components/icons.jsx, frontend/src/modules/flexible-forms/entity-modal/add-entity-modal.jsx, frontend/src/modules/flexible-forms/entity-modal/form-schema.js, frontend/src/modules/flexible-forms/entity-modal/modal.module.scss, frontend/src/modules/knowledge-lib/filter-modal.jsx, frontend/src/modules/knowledge-lib/filter.module.scss, frontend/src/modules/onboarding/affiliation-option.jsx, frontend/src/modules/onboarding/form-four.jsx, frontend/src/modules/onboarding/form-one.jsx, frontend/src/modules/onboarding/form-three.jsx, frontend/src/modules/onboarding/form-two.jsx, frontend/src/modules/onboarding/styles.module.scss, frontend/src/modules/onboarding/view.jsx, frontend/src/pages/_app.jsx, frontend/src/pages/landing/index.jsx, frontend/src/styles/btns.scss, frontend/src/styles/input.scss, frontend/src/styles/vars.scss, frontend/src/utils/final-field.jsx, frontend/src/utils/forms/field-template.js, frontend/src/utils/forms/form-select.js, frontend/src/utils/forms/wrap-if-additional.js
---
- https://app.asana.com/0/0/1205366649507606
=> Update onboarding page style

frontend/src/pages/forum/[channelName].jsx, frontend/src/pages/forum/channel.module.scss
[#1590] Call all forums and my forums endpoint to show in details channel page
=> FE: Add public forum list in details channel page

backend/resources/gpml/config.edn, backend/src/gpml/db/jdbc_util.clj, backend/src/gpml/db/plastic_strategy/bookmark.clj, backend/src/gpml/db/plastic_strategy/bookmark.sql, backend/src/gpml/db/topic.clj, backend/src/gpml/domain/types.clj, backend/src/gpml/handler/browse.clj, backend/src/gpml/handler/plastic_strategy/bookmark.clj, backend/src/gpml/service/plastic_strategy/bookmark.clj, backend/test/gpml/handler/browse_test.clj
* Implement API endpoint to handle plastic strategy bookmarks.
* Adapt browse API to add information about resources that are bookmarked by a specific plastic strategy.
=> 1611 plastic strategy bookmarks

frontend/src/components/autocomplete-form/autocomplete-form.jsx, frontend/src/components/autocomplete-form/style.module.scss, frontend/src/modules/workspace/ps/config.js, frontend/src/modules/workspace/ps/setup-team-form.jsx, frontend/src/modules/workspace/ps/setup-team-form.module.scss, frontend/src/modules/workspace/ps/setup-team-table.jsx, frontend/src/modules/workspace/ps/setup-team-table.module.scss, frontend/src/pages/workspace/[slug]/1-project-team/setup-team.js, frontend/src/pages/workspace/[slug]/1-project-team/setup-team.module.scss, frontend/src/pages/workspace/[slug]/index.js, frontend/src/pages/workspace/[slug]/layout.js, frontend/src/styles/base.scss, frontend/src/styles/dialog.scss, frontend/src/utils/api.js
=> PS Frontend: Section II - Setup Team

frontend/lingui.config.js, frontend/next.config.js, frontend/package.json, frontend/src/modules/landing/landing.jsx, frontend/src/pages/_app.jsx, frontend/src/pages/_document.jsx, frontend/src/pages/index.jsx, frontend/src/translations/languages.js, frontend/src/translations/locales/en.po, frontend/src/translations/locales/fr.po, frontend/src/translations/locales/pseudo.po, frontend/src/translations/utils.js, frontend/yarn.lock
---
- https://app.asana.com/0/0/1205680133857506
=> Add Lingui setup

backend/src/gpml/handler/plastic_strategy/file.clj
=> Fix RBAC permission on get-ps-files handler

backend/src/gpml/handler/stakeholder.clj
* Otherwise this will fail for those users that don't have a chat account.
---
- https://app.asana.com/0/0/1205766170365344
=> Check for chat_account_id before trying to update chat role

backend/src/gpml/handler/plastic_strategy/file.clj
=> Fix query params destructuring in get-ps-files

backend/resources/migrations/200-add-chat-channel-id-to-ps-model.up.sql, backend/src/gpml/boundary/adapter/chat/rocket_chat/core.clj, backend/src/gpml/boundary/port/chat.clj, backend/src/gpml/db/jdbc_util.clj, backend/src/gpml/db/plastic_strategy.clj, backend/src/gpml/db/plastic_strategy.sql, backend/src/gpml/db/plastic_strategy/team.sql, backend/src/gpml/handler/plastic_strategy/team.clj, backend/src/gpml/handler/programmatic/plastic_strategy.clj, backend/src/gpml/service/chat.clj, backend/src/gpml/service/plastic_strategy.clj, backend/src/gpml/service/plastic_strategy/team.clj
* Create RocketChat channel per plastic strategy when creating.
* Add PS team members to PS channel when they are created.
* Make sure we added new invited PS users to PS channel.
---
- https://app.asana.com/0/0/1205680133857491
=> 1611 ps forum

backend/src/gpml/db/topic.clj
[Re #1611]
* This is a convinience to the FE.
=> Return empty array instead of null if there aren't ps bookmarks

backend/resources/gpml/config.edn, backend/src/gpml/handler/chat.clj
* As per internal decision this endpoint now is public.
=> Remove auth and RBAC restriction from get-all-channels

backend/src/gpml/handler/badge.clj
[Re #1611]
We need to support assinging and unassigning badge by its unique name since it is more convinient for FE to avoid relying on extra GET call for getting the badge ids.
We have decided to support both name and id properties here because it's easier and we can share same specs for the GET and POST Assign Badge endpoints, regarding path params.
=> 1611 Support using Badge name in /api/badge/assign endp.

backend/src/gpml/db/badge.clj, backend/src/gpml/handler/badge.clj
* Add multiple results to signal when a badge or entity does not exist.
=> Improve batch assignment error handling

backend/src/gpml/db/topic.clj
* Also fixed the broken formatting of the file.
=> Add representative-group prop to entity connections in topic query

frontend/src/modules/entity-detail/styles.module.scss, frontend/src/modules/entity-detail/view.jsx, frontend/src/modules/stakeholder-detail/styles.module.scss, frontend/src/modules/stakeholder-detail/view.jsx, frontend/src/utils/misc.js
---
- https://app.asana.com/0/0/1205775102406853
=> Add badges in detail view

frontend/src/pages/workspace/[slug]/7-final-review/index.js, frontend/src/pages/workspace/[slug]/7-final-review/index.module.scss, frontend/src/pages/workspace/[slug]/layout.js, frontend/src/styles/vars.scss
---
- https://app.asana.com/0/0/1205724148514809
=> PS: Final Review

frontend/src/modules/forum/forum-iframe.jsx, frontend/src/modules/forum/forum-members.jsx, frontend/src/modules/forum/forum-members.module.scss, frontend/src/modules/forum/forum-modal.jsx, frontend/src/modules/workspace/view.jsx, frontend/src/pages/forum/[channelName].jsx, frontend/src/pages/forum/index.jsx, frontend/src/pages/forum/index.module.scss
---
- https://app.asana.com/0/0/1205793380920105
=> Fix Bug with Forums in Workspace

frontend/src/pages/workspace/[slug]/2-stakeholder-consultation/stakeholder-map.js, frontend/src/pages/workspace/[slug]/2-stakeholder-consultation/stakeholder-map.module.scss
---
- https://app.asana.com/0/0/1205859476231747
=> Ability to remove stakeholders from the Stakeholder Map view

frontend/src/components/forum-card/forum-card.jsx, frontend/src/modules/forum/my-forums.jsx, frontend/src/pages/forum/index.jsx
Replace "_", "-" with " " (space) in channel names throughout
---
- https://app.asana.com/0/0/1205866886400302
=> forum: Replace hyphen, underscore w/ space in title

frontend/src/modules/workspace/ps/resource-cards.jsx, frontend/src/modules/workspace/view.jsx, frontend/src/pages/[type]/[id].jsx, frontend/src/pages/forum/index.module.scss, frontend/src/pages/workspace/[slug]/3-legislation-policy/country-policy.module.scss
1. Run the app via ngrok
```
ngrok http 3001
```
2. Test title and meta tags with
[https://metatags.io/](https://metatags.io/)
---
- https://app.asana.com/0/0/1205724148705607
=> feat: Add head title, desc & meta og tags

frontend/src/pages/workspace/[slug]/2-stakeholder-consultation/stakeholder-map.js, frontend/src/pages/workspace/[slug]/3-legislation-policy/country-policy.module.scss
---
- https://app.asana.com/0/0/1205859571336277
=> PS: Rename strength column to initiatives & fix tags filtering FE side

frontend/src/modules/workspace/ps/config.js, frontend/src/modules/workspace/styles.module.scss
---
- https://app.asana.com/0/0/1205831994418310
=> PS: Update ps config to add new 11 countries

frontend/src/modules/workspace/styles.module.scss, frontend/src/modules/workspace/view.jsx, frontend/src/pages/landing/index.jsx, frontend/src/pages/workspace/plastic-strategies/index.js, frontend/src/pages/workspace/plastic-strategies/index.module.scss
=> Workspace misc

frontend/src/components/nav/menu-item.jsx, frontend/src/components/nav/nav-mobile.jsx, frontend/src/layouts/new-layout.js, frontend/src/modules/knowledge-lib/filter-bar.jsx, frontend/src/modules/knowledge-lib/resource-view.jsx, frontend/src/modules/knowledge-lib/style.module.scss, frontend/src/pages/landing/index.jsx, frontend/src/pages/landing/index.module.scss, frontend/src/store.js, frontend/src/styles/base.scss
---
- https://app.asana.com/0/0/1205820008809430
- https://app.asana.com/0/0/1205886260237395
=> Update knowledge library mobile view

frontend/src/pages/landing/index.jsx
---
- https://app.asana.com/0/0/1205932168751838
=> fix: Three suggested tags link to the wrong links

frontend/src/modules/workspace/ps/setup-team-form.jsx, frontend/src/modules/workspace/ps/setup-team-form.module.scss
- Remove stakeholders from UIStore that already prefetched.
- Use `/api/community` endpoint to get stakeholders by keyword/search value.
- Show organisation name from affiliation prop.
- Set minimum search character: 3
- Set limit search results: 5
---
- https://app.asana.com/0/0/1205859572510571
=> PS: Fix add team member & show organisation

backend/resources/gpml/config.edn, backend/src/gpml/boundary/adapter/chat/rocket_chat/core.clj, backend/src/gpml/boundary/port/chat.clj, backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj
- We don't want to get child channels created inside these channels. That information will be fetched in other operation.
---
- https://app.asana.com/0/0/1205942631322692
=> Impl. channel details and discussions

frontend/src/modules/forum/forum-iframe.jsx
Please reset this branch when you have checkout it before by running this command
```
git reset --hard origin/bug/forum-iframe-double-loading
```
=> forum: Fix double-loading by listening custom event "loaded"

backend/src/gpml/handler/detail.clj
* The operation-allowed? check will allow only admins as the "stakeholder/delete" is not attached to any specific role.
=> Allow deleting stakeholder if the callee is an admin

backend/src/gpml/service/chat.clj
* We filter PS channels by default in the BE as they shouldn't be available in the default get-public-channels API response. I added an option to not filter them when we need to get the details of a channel.
=> Don't filter PS channel when getting channel details

backend/src/gpml/service/chat.clj, frontend/src/modules/workspace/view.jsx, frontend/src/pages/forum/[channelName].jsx, frontend/src/pages/forum/index.jsx, frontend/src/pages/workspace/[slug]/forum/index.js, frontend/src/pages/workspace/[slug]/layout.js, frontend/src/store.js
=> Fix: Unable to fetch details for PS channel

ci/build.sh, ci/test/basic.sh, ci/test/token.sh
* Use `set -Eeuxo pipefail` in build.sh
* Improve log placement
These don't directly fix the build (which is green in this PR but still red in `main`, misteriously) but at least should result in clearer CI failures.
=> Improve buiild.sh

.semaphore/semaphore.yml
https://semaphoreci.com/blog/deprecating-ubuntu-18.04-in-semaphore
Fixes https://github.com/akvo/unep-gpml/issues/1789
=> semaphore.yml: upgrade Ubuntu image

ci/build.sh, ci/test/basic.sh, db/script/dump-db.sh, db/script/enable-pg-logging.sh
* Use clearer `--no-TTY` option
* Increase `wait4ports` timeout
=> Increase `wait4ports` timeout

backend/Dockerfile
Fixes https://github.com/akvo/unep-gpml/issues/1776
=> Use JDK 21

backend/src/gpml/handler/browse.clj, backend/test/gpml/handler/browse_test.clj
This will help diagnosing some sporadic issues that had been present in Sentry for a long while.
=> Improve `gpml.handler.browse` logging

backend/src/gpml/handler/monitoring.clj
It was implemented but unused till now.
=> Do use our custom Sentry appender

backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj, backend/src/gpml/service/plastic_strategy.clj, backend/src/gpml/service/plastic_strategy/team.clj
Similar to https://github.com/akvo/unep-gpml/pull/1818 but for leaving instead of joining.
=> Refactor `/leave` to use persistence

backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj
Namely /all, /public, /private, /user/channel
=> Return users from DB tables in remaining endpoints

backend/src/gpml/boundary/adapter/chat/ds_chat.clj, backend/src/gpml/handler/chat.clj
* Adapt some calls to new schema
* Correctly use `find
=> Misc fixes

backend/src/gpml/handler/chat.clj
=> Remove some authorization checks

backend/dev/src/dev.clj, backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj
Also: add a Swagger schema to `POST /api/chat/user/account`
=> DSC: use `<first name> <last name>` as the username

backend/.dir-locals.el, backend/resources/migrations/209-create_pinned_links.up.sql, backend/src/gpml/boundary/adapter/chat/ds_chat.clj, backend/src/gpml/boundary/port/chat.clj, backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj, backend/src/gpml/util/malli.clj
=> Implement Pinned Links endpoints

backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj
Adds the last detail to consider Pinned Links backend as complete
=> Refine pinned links authorization

backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj
=> Implement GET discussions endpoint

backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj
=> Implement admin DELETE Pinned Link

backend/seeder/gpml/seeder/dummy.clj, backend/src/gpml/db/stakeholder.clj, backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj, backend/src/gpml/service/file.clj
Should work for newly created users
=> Propagate profile picture URLs to DSC

frontend/src/layouts/new-layout.js, frontend/src/modules/email-signup/view.jsx, frontend/src/modules/landing/menu-bar.jsx, frontend/src/pages/_app.jsx, frontend/src/styles/base.scss, frontend/src/utils/profile.js
---
- https://app.asana.com/0/0/1206300761668485
- https://app.asana.com/0/0/1206571178316954
=> Remove onboarding

frontend/src/modules/signup-old/signup-form.jsx
---
- https://app.asana.com/0/0/1206768729895971
=> Fix edit form seeking and offering

backend/src/gpml/service/plastic_strategy/team.clj
Chat account creation is implicity with the `join-channel` function.
(Internal change - no changes observable)
=> `service.plastic-strategy`: discard now-redundant chat account creation

backend/resources/gpml/duct.base.edn, backend/src/gpml/boundary/port/chat.clj, backend/src/gpml/handler/chat.clj, backend/src/gpml/service/chat.clj, backend/src/gpml/service/plastic_strategy/team.clj, backend/src/gpml/util/email.clj, backend/src/gpml/util/http_client.clj
Sample email content:
```
Mr. Foo Bar (User ID 10005 - abc@abc.net) has requested to create a chat channel with the following details:
Name - Ym62p9Sx4E4U05NkfIX9x0AftW
Description - ASasdlkjaslkda
Privacy - public
Feel free to create such a channel.
```
Swagger:
=> Implement `api/chat/channel/request-new` endpoint

backend/src/gpml/boundary/adapter/chat/ds_chat.clj, backend/src/gpml/handler/stakeholder.clj, backend/src/gpml/service/stakeholder.clj, backend/src/gpml/util/result.clj
This fixes the HTTP 500 that was being seen when promoting a user to admin.
=> `handler.stakeholder`: correctly update the moderator attribute

backend/src/gpml/db/jdbc_util.clj, backend/src/gpml/handler/plastic_strategy.clj, backend/src/gpml/service/plastic_strategy.clj, backend/src/gpml/util/http_client.clj
This was an old latent bug - most likely it never worked
=> Fix PUT `/api/plastic-strategy/{country}` endpoint

backend/src/gpml/db/badge.clj, backend/src/gpml/db/chat_curated_channel.clj, backend/src/gpml/db/file.clj, backend/src/gpml/handler/badge.clj, backend/src/gpml/handler/programmatic/badge.clj, backend/src/gpml/scheduler/brs_api_importer.clj, backend/src/gpml/service/chat.clj, backend/src/gpml/service/chat_curated_channel.clj, backend/src/gpml/service/file.clj, backend/src/gpml/service/invitation.clj, backend/src/gpml/service/plastic_strategy/file.clj, backend/src/gpml/util/email.clj, backend/src/gpml/util/result.clj
> Part of https://github.com/akvo/unep-gpml/issues/1880
=> Use `failure` in misc places

backend/dev/src/dev.clj, backend/seeder/gpml/seeder/dummy.clj, backend/src/gpml/db/stakeholder.clj, backend/src/gpml/service/chat.clj, backend/src/gpml/service/invitation.clj, backend/src/gpml/service/plastic_strategy/team.clj, backend/src/gpml/service/stakeholder.clj, backend/test/gpml/db/initiative_test.clj, backend/test/gpml/db/updater_test.clj
> Part of https://github.com/akvo/unep-gpml/issues/1880
=> `gpml.db.stakeholder`: use `failure`

backend/src/gpml/handler/detail.clj
Prevents issues similar to those found in https://github.com/akvo/unep-gpml/pull/1883
=> Open a map

backend/dev/src/dev.clj, backend/project.clj, backend/src/dev/gethop/sql_utils.clj
This single-file dependency was swallowing some exceptions.
=> Vendor `dev.gethop.sql-utils`, use full exception logging

backend/resources/migrations/212-add-rbac-context-for-pseudo-country-ps.up.sql, backend/src/gpml/handler/plastic_strategy/team.clj, backend/src/gpml/service/permissions.clj, backend/src/gpml/service/plastic_strategy/team.clj
=> Fix Plastic Strategy endpoint for `Country A`

backend/src/gpml/boundary/adapter/chat/ds_chat.clj, backend/src/gpml/handler/detail.clj, backend/src/gpml/util/result.clj
* `handler.detail`: treat DSC user deletion idempotently
* `util.result`: assoc the file correctly
* `ds-chat`: also indicate the `:status` in failures
=> `handler.detail`: treat DSC user deletion idempotently

backend/.clj-kondo/config.edn, backend/project.clj, backend/resources/gpml/duct.base.edn, backend/src/duct_hierarchy.edn, backend/src/gpml/scheduler/chat_message_summarizer.clj
Empty implementation - adding to see if it indeed runs every 5 minutes and logs that to GCP.
=> Draft `:gpml.scheduler/chat-message-summarizer`

backend/src/gpml/scheduler/chat_message_summarizer.clj, backend/src/gpml/timbre_logger/json.clj
Silences some parts that were noisy on GCP today.
=> Quieter logs

backend/src/gpml/boundary/adapter/chat/ds_chat.clj
Today I realised that https://deadsimplechat.com/developer/rest-api/get-user has a severe flaw - if you don't specify email/username to this endpoint, they'll be nulled out in their database.
=> DSC `update-user-account`: work around the API nulling out fields

backend/src/gpml/handler/stakeholder.clj, frontend/src/modules/signup-old/signup-form.jsx, frontend/src/modules/signup-old/styles.module.scss, frontend/src/modules/stakeholder-detail/styles.module.scss, frontend/src/modules/stakeholder-detail/view.jsx, frontend/src/pages/unsubscribe-chat/index.jsx, frontend/src/pages/unsubscribe-chat/index.module.scss
---
- https://app.asana.com/0/0/1207202392061464
=> Add enable/disable notification

.semaphore/semaphore.yml, docker-compose.ci.yml, docker-compose.override.yml, docker-compose.yml
=> [#2022] Remove unsupported `docker compose` settings/flags

frontend/src/pages/page/[slug].jsx, frontend/src/pages/page/style.module.scss
---
- https://app.asana.com/0/0/1207412601872871
=> Add contact form

frontend/src/pages/landing/index.jsx, frontend/src/pages/landing/index.module.scss
---
- https://app.asana.com/0/0/1207407748109996
=> Add partners strapi api

frontend/src/pages/workspace/[slug]/index.js, frontend/src/pages/workspace/[slug]/layout.js
---
- https://app.asana.com/0/0/1207558575527305
=> Add a link for each country

backend/src/gpml/db/topic.clj, backend/src/gpml/domain/related_content.clj, backend/src/gpml/domain/resource.clj, backend/src/gpml/domain/types.clj, backend/src/gpml/handler/comment.clj, backend/src/gpml/handler/like.clj, backend/src/gpml/handler/resource.clj
- Same `resource` table
- topic=`data_catalog`
=> Feat: Support of `Data Catalog` as resource

backend/resources/gpml/duct.base.edn, backend/resources/migrations/219-adjust-country-group-sequence.up.sql, backend/resources/migrations/220-add-delete-cascade-to-country-group-country.up.sql, backend/src/gpml/db/country_group.clj, backend/src/gpml/db/country_group.sql, backend/src/gpml/handler/country_group.clj, backend/test/gpml/db/landing_test.clj, backend/test/gpml/handler/policy_test.clj
---
- https://app.asana.com/0/0/1207643740316555
=> Add a POST/DELETE method for /country-group endpoint

backend/src/gpml/handler/search.clj
As per suggestion from AI expert ¯\_(ツ)_/¯
=> Feat: Reduce request temperature

backend/resources/migrations/222-add-v-resources-view.up.sql
As per request, we "expand" both values going from `country` to `country_group` where the country is member of, and expading the list of countries for a particular `country_group`
=> Feat: Update the way we calculate `country` and `country_group`

backend/resources/migrations/222-add-v-resources-view.up.sql, db/docker-entrypoint-initdb.d/001-init.sql
- categoryId
- subcategoryId
- arcgislayerId
=> Feat: Add extra fields to `dataset` type

backend/src/gpml/handler/browse.clj
---
- https://app.asana.com/0/0/1207955520014202
=> Add orderBy created on /browse endpoint

frontend/src/hooks/useQueryParameters.jsx
---
- https://app.asana.com/0/0/1207930206919397
=> Change routing -query parameters

backend/src/gpml/db/topic.clj, backend/src/gpml/handler/browse.clj
---
- https://app.asana.com/0/0/1208329049535032
=> Implement /resources tag filter to be case insensitive

backend/resources/gpml/duct.base.edn, backend/src/gpml/db/tag.clj, backend/src/gpml/db/tag.sql, backend/src/gpml/handler/tag.clj
---
- https://app.asana.com/0/0/1208251701257182
=> Implement delete and migrate tag

frontend/src/components/withAuth.js, frontend/src/pages/_error.jsx, frontend/src/pages/organisation/[id].jsx, frontend/src/pages/stakeholder/[id].jsx, frontend/src/translations/locales/en.po, frontend/src/translations/locales/es.po, frontend/src/translations/locales/fr.po, frontend/src/translations/locales/pseudo.po
---
- https://app.asana.com/0/0/1208028539780823
=> 404,403 pages

backend/src/gpml/domain/types.clj
Issue:  https://app.asana.com/0/1204455129773834/1208756134979842
=> Include `project` as valid type

frontend/src/pages/knowledge-hub/index.js, frontend/src/pages/knowledge-hub/index.module.scss
---
- https://app.asana.com/0/0/1208509860005249
=> update knowledge hub

backend/resources/migrations/228-setup-project-submission-review.up.sql, backend/resources/migrations/229-create-project-like-table.up.sql, backend/resources/migrations/230-adjust-resources-view.up.sql, backend/src/gpml/db/submission.sql, backend/src/gpml/db/topic.clj, backend/src/gpml/domain/types.clj, backend/src/gpml/handler/submission.clj
---
- https://app.asana.com/0/0/1208636754889049
=> Implement /search and /resources for project resource

frontend/src/hooks/useReplacePlaceholders.js, frontend/src/modules/country-dashboard/charts/MSWGeneration.tsx, frontend/src/pages/countryOverview/index.jsx, strapi/src/api/category/controllers/category-replace.js, strapi/src/api/category/routes/category-replace.js
=> Revert "Jasminalazic/country dashboard improvements"

backend/resources/gpml/duct.base.edn, backend/src/gpml/db/country_group.clj, backend/src/gpml/db/country_group.sql, backend/src/gpml/handler/country_group.clj
---
- https://app.asana.com/0/0/1208714302958900
=> Implement PATCH /country-group/:id

backend/src/gpml/db/community.clj
---
- https://app.asana.com/0/0/1208684752087496
=> Adjust /api/community response fields

backend/src/gpml/handler/search.clj
---
- https://app.asana.com/0/0/1208636754889074
=> Replace `images` prop with `image` url in /search response

backend/src/gpml/service/plastic_strategy/team.clj, backend/test/mocks/boundary/adapter/chat/ds_chat.clj
---
- https://app.asana.com/0/0/1208900336767833
=> Fix bug when inviting users to plastic strategy

README.md
---
- https://app.asana.com/0/0/1208987635080012
=> Add backend development section on README.md

backend/resources/migrations/232-create-plastic-strategy-project-bookmark-table.up.sql
---
- https://app.asana.com/0/0/1209088600290599
=> Create plastic_strategy_project_bookmark table

backend/resources/migrations/233-add-missing-project-relation-on-delete-cascades.up.sql
---
- https://app.asana.com/0/0/1209750787313021
=> Add missing project relation on delete cascades

backend/src/gpml/handler/organisation.clj
---
- https://app.asana.com/0/0/1209724498253480
=> Make organisation country field optional

strapi/config/api.js, strapi/src/api/category/controllers/category-replace.js, strapi/src/api/layer/controllers/layer-countries-controller.js, strapi/src/api/layer/routes/layer-countries.js, strapi/src/api/layer/services/populateCountries.js, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
=> update populate country value

frontend/src/hooks/useLayerInfo.js
Add error handle to update state
=> Populate country value

frontend/src/hooks/useLayerInfo.js, frontend/src/translations/locales/es.po, frontend/src/translations/locales/fr.po
=> add new line for overlap text

frontend/src/hooks/useLayerInfo.js, strapi/src/api/data-layer/controllers/data-layer.js, strapi/src/api/data-layer/routes/data-layer.js, strapi/src/api/data-layer/services/data-layer.js, strapi/src/api/layer-collection/content-types/layer-collection/schema.json, strapi/src/api/layer-collection/controllers/layer-collection-controller.js, strapi/src/api/layer-collection/controllers/layer-collection.js, strapi/src/api/layer-collection/routes/layer-collection-value.js, strapi/src/api/layer-collection/routes/layer-collection.js, strapi/src/api/layer-collection/services/layer-collection.js, strapi/src/api/layer/controllers/layer-countries-controller.js, strapi/src/api/layer/services/populateCountries.js, strapi/types/generated/contentTypes.d.ts
=> add-new-table

frontend/src/pages/add-content/index.jsx, frontend/src/pages/admin/individuals.jsx, frontend/src/pages/admin/organisation.jsx, frontend/src/pages/admin/resource.jsx
---
- https://app.asana.com/0/0/1209724987639413
- https://app.asana.com/0/0/1209709609275663
=> update admin, case study

frontend/src/hooks/useLayerInfo.js, strapi/src/api/layer-collection/controllers/layer-collection-controller.js, strapi/src/api/layer-collection/routes/layer-collection-value.js
add new custom layer controller
=> add new custom layer controller

strapi/config/env/production/server.js, strapi/config/server.js
=> add request timeout

frontend/src/pages/countryOverview/index.jsx, strapi/src/api/layer/controllers/layer-countries-controller.js, strapi/src/api/layer/routes/layer-countries.js, strapi/src/api/layer/services/populateCountries.js
=> add data layer chunk

frontend/src/pages/countryOverview/index.jsx
=> fix wrong url

frontend/src/pages/countryOverview/index.jsx
=> continue when failed

backend/src/gpml/boundary/adapter/chat/ds_chat.clj, backend/src/gpml/boundary/port/chat.clj, backend/src/gpml/scheduler/chat_message_summarizer.clj
---
- https://app.asana.com/0/0/1210158828770453
=> Implement sub-channel notification backend

frontend/src/components/map-and-layers/sidebar/index.jsx
=> add selected category

frontend/src/components/map-and-layers/sidebar/index.jsx
=> add category by route

frontend/src/components/map-and-layers/sidebar/index.jsx, frontend/src/components/map-and-layers/sidebar/partials/categoriesNested.jsx
=> update category parent click

strapi/src/api/category/controllers/category-replace.js
=> round up decimals

backend/.clj-kondo/config.edn, backend/resources/gpml/duct.base.edn, backend/resources/migrations/234-create-notification-table.up.sql, backend/src/gpml/handler/notification.clj, backend/src/gpml/scheduler/chat_message_summarizer.clj
---
- https://app.asana.com/0/0/1210158828770457
=> Implement notification backend

frontend/src/components/map-and-layers/sidebar/index.jsx, frontend/src/components/map-and-layers/sidebar/index.module.scss, frontend/src/components/map-and-layers/sidebar/partials/categoriesNested.jsx, frontend/src/components/map-and-layers/sidebar/partials/subcategories.jsx
=> update maps mobile nav

backend/src/gpml/boundary/adapter/chat/ds_chat.clj, backend/src/gpml/boundary/port/chat.clj, backend/src/gpml/scheduler/chat_message_summarizer.clj
---
- https://app.asana.com/0/0/1210270610845484
=> Direct Messages notification

frontend/src/translations/locales/en.po, frontend/src/translations/locales/es.po, frontend/src/translations/locales/fr.po, frontend/src/translations/locales/pseudo.po
=> add missing translation

backend/src/gpml/service/chat.clj
---
- https://app.asana.com/0/0/1210865245689412
=> Fix /chat/channel/all returning empty users

frontend/src/modules/community-hub/detail-view.jsx
---
- https://app.asana.com/0/0/1211450340319622
=> add promote to admin
