ci/build.sh
ci/test/basic.sh

When the "basic.sh" script fails, show the docker-compose logs as it can contain useful information to debug why the CI environment did not start properly or show some exception
Part of #203

Show docker logs when build fails

---

backend/resources/gpml/config.edn
backend/src/gpml/auth.clj
backend/src/gpml/constants.clj
backend/src/gpml/handler/browse.clj
backend/src/gpml/handler/detail.clj
backend/test/gpml/auth_test.clj

Stakeholders and Organizations details should only be visible to
approved users. This change ensures that the API returns 404 for
unapproved/anonymous users when requesting these resources.

Restrict /details API access for private topics 

---

frontend/src/utils/trim.js

We have a user using Chrome 73 and String.replaceAll is not available:
In Chrome support for replaceAll started in version 85. More info:
https://caniuse.com/?search=replaceAll
Switch to use global `String.replace()`
> Global replace can only be done with a regular expression [...]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#using_global_and_ignore_with_replace

[#330] String.replaceAll is not available in old browsers

---

frontend/src/utils/forms/form-select.js

The sign up form shows the Other option when the name searched for is
not present in the list of options. This commit makes the other forms
behave similarly, when the Select list has the option added to the
list of options with a value -1. The organisation lists in the forms
already have this option added.

[#283] Show Other option when typing names not in search list

---

backend/test/gpml/handler/organisation_test.clj

We should anyway look for another parallel test approach for mailing support

Temporary fix to keep current mailing test support

---

backend/resources/gpml/config.edn
backend/src/gpml/db/review.sql
backend/src/gpml/db/submission.sql
backend/src/gpml/handler/review.clj
frontend/src/modules/profile/admin.jsx
frontend/src/modules/profile/preview.jsx
frontend/src/modules/profile/review.jsx
frontend/src/modules/profile/utils.js
frontend/src/modules/profile/view.jsx
frontend/src/utils/api.js

This pull request implements the basic approval workflow where reviewers (users with the roles REVIEWER or ADMIN) can be assigned as reviewers to specific resources.  
A new review section is added to the profile page of reviewers, where a list of all assigned resources can be seen. The reviewers can then accept or reject resources.  This status is visible to admins in the existing admin section. 
Known issues (or things to be done): 
- Allow both reviewers and admins to add a note when accepting/rejecting during the review or approval process. 
- Items that are once accepted or rejected by reviewers cannot be changed in their review status. 
- Items already approved (or declined) by admins are still shown to reviewers as items pending review. It may be confusing if the reviewer …

Basic implementation of Approval workflow

---

frontend/src/utils/final-field.jsx

When the /profile page is opened directly the tags are not *yet*
populated in the UIStore correctly, and the seeking.options,
offering.options, etc. in the profile form are not set correctly,
causing the profile page to crash. This commit fixes our final-field
Select CONTROL to not crash when options are not set.
This bug was probably present before, but have been exacerbated by the
change in 06882bdd3afa49e33f167b118cc78d1cc5ae93b6, which updates the
UIStore after a bunch of API calls finish, instead of updating the
data when each call finishes. This means the tags data often gets in
the UIStore after the profile data has been fetched.
Previously, fa87bd13b2472248ad4bae4a97507c42c3a0e8c8 tried to fix a
similar crash, but is only half the fix.
Closes #395

[#395] Fix crashes when opening /profile directly

---

backend/resources/gpml/config.edn
backend/src/gpml/constants.clj
backend/src/gpml/db/stakeholder.sql
backend/src/gpml/db/submission.sql
backend/src/gpml/handler/review.clj
backend/src/gpml/handler/stakeholder.clj
backend/src/gpml/handler/submission.clj
backend/src/gpml/handler/util.clj
backend/test/gpml/handler/stakeholder_test.clj
backend/test/gpml/handler/util_test.clj
frontend/src/modules/profile/stakeholders.jsx
frontend/src/modules/profile/utils.js
frontend/src/modules/profile/view.jsx
frontend/src/utils/misc.js

The UI is intentionally very basic, since this is an MVP and the eventual plan is to have different tabs for managing users (including approvals) and managing resources. This is the eventual design we wish to move towards, as per @loicsans design, but this would require bigger API changes and should be pushed to later.
The basic UI could use some basic CSS and styling improvements, though. @wayangalihpratama may be you could help with this, after this branch is merged, and when you have some time. I didn't spend any effort on CSS work on this branch. 
Issues to think about (or work on):
- Should admins be allowed to remove admin status of other admins? 
- Search functionality for quickly looking up users has not been added in the UI. The API supports searching for users using the email, …

Add basic UI and API end-points for changing roles for stakeholders

---

backend/src/gpml/db/browse.clj
backend/src/gpml/db/browse.sql
backend/src/gpml/db/detail.sql
backend/src/gpml/handler/browse.clj
backend/src/gpml/sql_util.clj
backend/test/gpml/handler/browse_test.clj
backend/test/gpml/sql_util_test.clj

Ideally, we'd like to filter by tag ID, but the initiatives use slightly different tags, searching by tag IDs is not possible. Instead, we allow searching by the actual tag name currently.

Add an additional parameter to the browse query to filter by tag

---

frontend/src/modules/signup/form.jsx

I'm not sure why we convert the data to String and back to Number, but this is a quick fix to get the signup working on the test server.

[#367] Fix tags data submitted on signup to be numbers

---

backend/resources/migrations/085-tag-topics.down.sql
backend/resources/migrations/085-tag-topics.up.sql

2f1e2b32afce5b1044859b9e356579577191b18e tried to add tags to some of
the topics, but this wasn't robust enough and caused builds to
fail. 87e753962afdbc67bc71b598b07bde1bd7be34d2 reverted this commit,
and this commit attempts to do it with more sanity checks.

[#363] Redo the tagging migration with more edge case checks

---

frontend/src/modules/about/about-us.jsx
frontend/src/modules/about/styles.scss

[#362] Make members and resources dynamic and remove the duplicated resources

---

frontend/src/modules/landing/new-home-static-content.js
frontend/src/modules/landing/new-home.jsx

- User will be redirected to overview/detail page if they are APPROVED user.
- if not logged in, login popup shown.
- if logged in but doesn't have profile, redirected to signup page.
- if logged in but not approved, show warning modal "We will review your sign-up request. Please, allow for 1 business day."

[#361] Homepage improvement

---

frontend/src/main.scss

[#361] Fix overlapping text on dropdown navigation menu item count

---

frontend/src/root.jsx
frontend/src/utils/profile.js

- For this problem (sign in / sign up in auth0 but not filling signup form on portal),
I think we can change the signin button to a user icon, and if user click profile that will going to `/signup` page (same as when user click Join GPML btn).

[#361] Fix bug: sign in, unable access the profile

---

frontend/src/modules/browse/view.jsx

[#372] Fix bug: show only resources on browse view when click all resource from nav

---

frontend/src/modules/events/form.jsx
frontend/src/modules/landing/new-home.jsx

- date format caused the difference between date on event detail and edit form
- need to parse datetime + offset time to form to get same value between event details and edit form

361 fe event content date difference on form

---

backend/src/gpml/db/review.sql
backend/src/gpml/handler/review.clj

- this PR support additional and optional `only` query arg
- possible values: `only=resources` or `only=stakeholders`
eg: `review-status=PENDING&page=1&limit=10&only=resources`

[#478] Filter/split GET review API call by resources or stakeholders

---

backend/resources/gpml/config.edn
backend/resources/migrations/107-topic-stakeholder-auth-table.down.sql
backend/resources/migrations/107-topic-stakeholder-auth-table.up.sql
backend/src/gpml/db/topic_stakeholder_auth.clj
backend/src/gpml/db/topic_stakeholder_auth.sql
backend/src/gpml/handler/auth.clj

- `GET api/auth/<topic-type>/<topic-id>`
List of stakeholders-auth-details for a specific topic
- `POST api/auth/<topic-type>/<topic-id>`
body `{"stakeholders": [{"id": 10001, "roles": ["owner"]}, {"id": 10002, "roles": ["owner"]}]}`  
For a specific topic, add auth roles for each stakeholder included in body payload
- `GET api/auth/<topic-type>/<topic-id>/<stakeholder-id>`
stakeholder-auth-details for a specific topic and stakeholder
- `POST api/auth/<topic-type>/<topic-id>/<stakeholder-id> `
body `{"roles": ["owner"]}`  
Add roles for a specific stakeholder and topic
- `PUT api/auth/<topic-type>/<topic-id>/<stakeholder-id> `
body `{"roles": ["owner"]}`  ||  `{"roles": []}`  
Update roles for a specific topic
- `DELETE api/auth/<topic-type>/<topic-id>/<stakeholder-id>`
Delete …

[#567] Auth multiple stakeholders to one resource

---

backend/resources/gpml/config.edn

This integrant key doesn't use the same set of credentials as the
auth0 constant. Reverting.

[#601] Fix auth0 misconfiguration for gmpl.handler.env/get

---

backend/src/gpml/db/stakeholder.sql

This was added by mistake due to merge conflict. This line doesn't
exist in the main branch.

[#601] Remove unnecessary column in stakeholder-by-email

---

backend/resources/migrations/124-fix-initiative-association.down.sql
backend/resources/migrations/124-fix-initiative-association.up.sql
backend/src/gpml/handler/initiative.clj

Initiative associations were using the table `project` for the
associations, which is deprecated. This commit references to the
table `initiative` and removes the link to `project`.

[#607] Fix initiative associations

---

backend/src/gpml/db/landing.sql
backend/src/gpml/sql_util.clj
backend/test/gpml/sql_util_test.clj

We should only show approved topics for end users. Therefore we are modifying the topic queries to consider only the topics with `review_status=APPROVED`.

592 resource counting mismatch

---

backend/src/gpml/handler/community.clj

* It was being discarded in the filters map construction.

[#699] Add missing affiliation filter to community API

---

backend/resources/gpml/config.edn
backend/resources/migrations/141-add-non-member-organisation-to-topic-type-enum.up.sql
backend/src/gpml/db/submission.sql

NOTE:
Even though `topic` in application level only refers to the knowledge
library topics, the `topic_type` enum seems to have been referenced
by a lot of tables and is used in queries like submissions and
reviews. For this reason, `non_member_organisation` has also been
added here even though it's not a real topic type. (And neither are
tags, stakeholders, organisations etc.. that already exist there
for the same reason.)

[#764] Submission endpoint for non member orgs

---

backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj
backend/test/gpml/handler/browse_test.clj

* Supported fields: title, description and id. If not provided
defaults to start_data/created date.
Closes #997

[#997] Add orderBy param to browse API

---

backend/resources/gpml/config.edn

* We need to think about how to interpret the tree like structure
return by this endpoint because the schema coercion is removing it
since it is not specified.

[#1073] Disable reitit responses coercion for GET comment

---

ci/k8s/deployment.yml.template

This reverts commit 01ace6e96cc808249190f249eb7667638aad7cd6.
I'm not yet quite sure why, but deploying to production has recently been failing because the new pod can't connect to the DB.
The solution has been to delete the new pod, which somehow leads K8 to believe that the rolling update is done.
It still recreates the pod for the new version because the new deployment revision demands it and the old one is removed.
When the new pod is the only one starting, then the update goes over smoothly.
At the moment, I cannot explain why this is happening only in production and not on test.
I assume it has to do with test being less active, but due to a lack of logs to debug, and since it looks like running a singular pod is the solution (or workaround, depends on how you look at it), …

Revert "[#60] Added rolling strategy"

---

backend/src/gpml/db/organisation.sql
backend/src/gpml/handler/stakeholder.clj
backend/src/gpml/pg_util.clj

* Handle `unique-violation-constraint` exception when creating an organisation with a name that already exists.
* If the existing organisation is a `non-member` we replace it with the new organisation which is a member.

1121-1147 Non-member to member org conversion in sign up

---

ci/k8s/deployment.yml.template

Removing the strategy definition just applied default values,
which wasn't very helpful and didn't solve the problem
we were facing of the inability to connect to the DB with 2 instances.

ci: Use Recreate deployment strategy

---

backend/src/gpml/handler/detail.clj

* Fix tag update when new tag creation is required as part of the update.
* Only update tags if there are tags to update.

1174 Fix detail API tags update deleting existing tags when creating new ones

---

backend/resources/migrations/150-fix-populate-stakeholder-tag-relation-category.down.sql
backend/resources/migrations/150-fix-populate-stakeholder-tag-relation-category.up.sql

* The previous migration(149) had an incorrect statement that makes the
UPDATE miss all the existing rows.
* See #1209
Closes #1209

[#1209] Fix populate tag_relation_category update

---

backend/resources/gpml/config.edn
backend/src/gpml/db/landing.clj
backend/src/gpml/db/landing.sql
backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj
backend/src/gpml/handler/landing.clj
backend/test/gpml/db/topic_test.clj

* Slightly improve topic query performance by removing duplicated rows in the result set.
* Add count for capacity building.
* Add logging in the browse API to check query performance.

Refactor topic query to improve performance

---

backend/src/gpml/db/event.sql
backend/src/gpml/db/initiative.sql
backend/src/gpml/db/policy.sql
backend/src/gpml/db/resource.sql
backend/src/gpml/db/technology.sql
backend/src/gpml/handler/detail.clj
backend/src/gpml/handler/initiative.clj

* Refactor tags retrieval in detail API and initiative GET handler to use the generic `get-resource-tags` DB function. That makes maintenance and bug fixes easier.
* Remove legacy `tags-by-id` DB functions (they were replaced by `get-resource-tags`).

1237 refactor and fix resource detail tag retrieval

---

backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj

* We need to know the count for specific tags when filtering
browsing for resources. So, I added an option to include the specified
tags count based on the result of the topics browsing query.
* Closes #1243

[#1243] Add option to include tags count in the browse results

---

backend/src/gpml/db/landing.clj
backend/src/gpml/db/landing.sql

* I had to refactor the landing DB layer regarding this count as it
was doing some assumptions that weren't right. One and most important,
it wasn't considering multiple transnational groups for the same
resource and their countries. Because a resource can be directly
related to a transnational, mutiple or countries within them.
* Closes #1255

[#1255] Fix resource count per transnational group

---

backend/resources/migrations/153-remove-default-avatar-pic-from-stakeholder.up.sql
backend/src/gpml/handler/stakeholder.clj
backend/test/gpml/handler/profile_test.clj

This PR contains:
- Stop of default avatar generation for stakeholders when creating them.
- DB Migration for removing default avatar images for existing stakeholders.
See #1256 for more details.

1256 remove default stakeholder avatar and stop generating them

---

backend/src/gpml/handler/stakeholder.clj

[Closes #1265]
Fix of update profile functionality for stakeholders by only looking into the
agreed canonical representation of "tags" property in the API request,
instead of merging "seeking" and "offering" properties, that should all be
sent as "tags" by FE.
We still cannot provide a params spec for the endpoint, since we need to agree
with FE not to sent optional properties as "null" in order to comply with the
Spec.

Fix update profile PUT endpoint for stakeholders

---

backend/src/gpml/db/organisation_detail.sql

[Closes #1280]
Added image property for the query to retrieve each related resource belonging
to an organization. The relationship can be set directly to the organization
or an stakeholder belonging to a given organization, but we cover both cases.
This allows FE to display the image when viewing the related resources of an
organization.
We keep using same "image" property name returned by the query in order to
keep consistence and be able to use this as stable/expected property name
regardless of the resource type.

Add image to organization's related content info

---

backend/resources/gpml/config.edn
backend/src/gpml/constants.clj
backend/src/gpml/handler/export.clj

* I also refactored a bit the arguments of each function to accept a
configuration map including the db-spec and the app-domain. That is
just in case we need to implement the same for other tables.
* Closes #1296

[#1296] Add platform links to entities export

---

backend/resources/gpml/config.edn
backend/src/gpml/auth.clj
backend/src/gpml/handler/stakeholder.clj
ci/k8s/deployment.template.yml
docker-compose.yml

* This middleware will be used to validate the tokens with Auth0
Actions application client's audience. The caller you have permissions
to use the Stakeholder API to retrieve sensitive information about the
users registered in the platform. It will be used by Auth0 Actions to
inject custom JWT claims in the IdToken to enhance the token
information in single sign-ons.
* Closes #1299

[#1299] Add programmatic access auth middleware for auth0 actions

---

backend/src/gpml/db/topic.clj

* I also changed the tags aggregation to filter out null values as it
is a similar case to the geo-coverage aggregates.
* Closes #1304

[#1304] Don't coalesce geo-coverage aggregates to zero values

---

backend/src/gpml/db/topic.clj

* This problem arises primarely because of duplicated tags. We have to
address this issue soon and make tag names unique and lower-cased.

Fix capacity building count on browse API

---

backend/src/gpml/db/stakeholder.sql
backend/src/gpml/handler/stakeholder.clj

* Remove SQLException details from the response map
* Update expert `review_status` when signing up. Experts are created by Administrators but they need to finish the onboarding (sign up) to be seen on the platform. So, when they do and we know they are an expert we update their `review_status`.

1317 experts invitation and management

---

backend/resources/gpml/config.edn
backend/src/gpml/handler/landing.clj

* We were not getting the user details from the request. Therefore we
couldn't find the user specific bookmarks.

Fix landing API favorites/bookmark filter

---

backend/resources/gpml/config.edn
backend/src/gpml/auth.clj
backend/src/gpml/db/stakeholder.sql
backend/src/gpml/handler/stakeholder/expert.clj

* Restrict invite endpoint to admins only.
* Add `countries` filter to `/list` endpoint.
* Return `:stakeholder-email-already-exists` when trying to create a stakeholder with an existing email address.

1317 Experts API improvements and bugfixes

---

backend/resources/gpml/config.edn
backend/src/gpml/auth.clj
backend/src/gpml/db/stakeholder.sql
backend/src/gpml/handler/detail.clj
backend/src/gpml/handler/stakeholder/expert.clj
backend/src/gpml/handler/stakeholder/tag.clj

* Add more logging when sending email invitations. We need to know if they are sent properly or not.
* Unwrap expert tags.

1317 Add more logging to email invitations and unwrap experts tags

---

backend/resources/gpml/config.edn
backend/src/gpml/handler/organisation.clj
backend/src/gpml/pg_util.clj
backend/test/gpml/handler/organisation_test.clj

* For details about why this change, please refer to issue #1338.
* Add ISQLParameter conversion for PostgreSQL enum types
* Don't get stakeholder email if it's nil. If the user calling the API doesn't have an email (they should
because we inject the token claims in the request) we shouldn't try to
get the stakeholder. This will likely never happen but just in case
I'm adding this check.
* Closes #1338

1338 refactor organisation creation logic

---

ci/k8s/deployment.template.yml

* Looks like the backend container takes more than one minute
sometimes to actually start and K8s then restart the container until
it starts within the delay limit.

Increase backend container liveness and readiness delay

---

backend/resources/gpml/config.edn
backend/src/gpml/auth.clj
backend/src/gpml/handler/detail.clj
backend/src/gpml/handler/submission.clj

* Apart of fixing the logic to also consider reviewer permissions, I
also improved the error handling on the submission details
API. Following the same pattern as we've been doing lately of handling
exceptions and returning the correct status code depending on the
error. Including error details in the response body.
* See #1354
* Closes #1354

Fix submission and resources details unauthorized for reviewer

---

backend/resources/gpml/config.edn
backend/src/gpml/handler/event.clj
backend/src/gpml/handler/initiative.clj
backend/src/gpml/handler/policy.clj
backend/src/gpml/handler/resource.clj
backend/src/gpml/handler/technology.clj

* Handling exceptions, checking for SQLExceptions and adding extra
details in case the error is not a SQLException (the exception
message, might disclose sensitive information). In any case, this can
be improved by isolating each step when creating a new resource and
fail as fast, and as soon as possible.

[#1362] Improve error handling for resources POST endpoints

---

backend/resources/gpml/config.edn
backend/src/gpml/db/country-group.sql
backend/src/gpml/handler/stakeholder/expert.clj

* Implement `country_groups` filter in the experts list API.
* Also fixed the scope of reponse and params schemas.
* Fixed the error handling typos.

Implement country_groups filter in the experts list API

---

backend/src/gpml/handler/event.clj
backend/src/gpml/handler/initiative.clj
backend/src/gpml/handler/policy.clj
backend/src/gpml/handler/resource.clj
backend/src/gpml/handler/technology.clj

* There was a typo when associating the :error-details key.

Fix resources POST endpoints error responses

---

backend/resources/gpml/config.edn
backend/src/gpml/auth.clj
backend/src/gpml/db/resource/association.clj
backend/src/gpml/db/resource/association.sql
backend/src/gpml/db/topic_stakeholder_auth.clj
backend/src/gpml/db/topic_stakeholder_auth.sql
backend/src/gpml/domain/topic_stakeholder_auth.clj
backend/src/gpml/handler/auth.clj
backend/src/gpml/handler/detail.clj
backend/src/gpml/handler/review.clj
backend/src/gpml/util/regular_expressions.clj
backend/test/gpml/handler/auth_test.clj

* Refactored gpml.auth namespace to better handle errors (exceptions).
* Added the data model in domain for topic_stakeholder_auth.
* Added the new focal-point role logic to edit organisations auth
middleware. So we also check for that now.
* Handle maximum number of focal points per organisation.
* Added logic to check for organisation's resources that the focal points can edit.
* Closes #1368

[#1368] Implement focal-points auth role validation

---

backend/src/gpml/handler/submission.clj

* We should use the :created_by key and not the id. This bug was
introduced during a refactor to remove the `v_stakeholder_data` view
where the `id` was the actual stakeholder `id` but that is not the
case anymore.

Fix submission creator email

---

backend/src/gpml/db/submission.sql
backend/src/gpml/handler/submission.clj

This reverts commit 1e8c2e1958a2e7dc65dad976401af7e046013df3.
This revert is needed as the endpoint to allow setting this flag should be different (already moved to `/api/detail/{topic-type}/{topic-id}` PUT endpoint).

Revert "Allow `featured` prop in PUT Submission API" #1404

---

backend/resources/migrations/164-remove-invalid-stakeholder-tags-enforcing-tag-relation-category.up.sql

[Closes #1409]
On one hand we have removed corrupted stakeholder tags that were missing
`tag_relation_category` property, as specified in the issue.
Then, in order to avoid this issue to happen again, we have enforced the
missing property in the corrupt data, to fullfil backend expectations.

Enforce `tag_relation_category` in DB model #1409

---

backend/resources/gpml/config.edn
backend/resources/migrations/165-fix-duplicated-tags.up.sql
backend/src/gpml/handler/detail.clj
backend/src/gpml/handler/event.clj
backend/src/gpml/handler/organisation.clj
backend/src/gpml/handler/policy.clj
backend/src/gpml/handler/resource.clj
backend/src/gpml/handler/resource/tag.clj
backend/src/gpml/handler/stakeholder.clj
backend/src/gpml/handler/stakeholder/expert.clj
backend/src/gpml/handler/stakeholder/tag.clj
backend/src/gpml/handler/tag.clj
backend/src/gpml/handler/technology.clj

This PR contains:
- Get rid of duplicated tags, keeping current assignations between different resources, backporting the relationships to the remaining unique tags, once duplicated have been removed.
- Ensure uniqueness in tags creation. In this case, uniqueness is checked by lowercasing the tag name, to avoid duplicated tags with just different case.
- Remove duplicate relationships between tags and resources.
- Ensure uniqueness in relationships between tags and resources, once duplicates are gone.
- Make sure BE respect the tags as they have been received from FE, stopping converting tags to lowercase.

Fix duplicated tags and ensure new tags are stored respecting the case #1416

---

backend/resources/migrations/169-add-capacity-building-to-resources.up.sql
backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj
backend/src/gpml/handler/event.clj
backend/src/gpml/handler/initiative.clj
backend/src/gpml/handler/landing.clj
backend/src/gpml/handler/policy.clj
backend/src/gpml/handler/resource.clj
backend/src/gpml/handler/technology.clj

* We want to flag resources as 'capacity building' when
required. Previously only Events and Resources had this flag. Now we
are expanding it to all resources.
* This didn't exist in the following resources: Initiative, Policy and
Technology.
* Updated browse API to implement the 'capacity_building' filter.
* Updated browse API to handle errors.
* Updated landing API to implement the 'capacity_building' filter.
* Cleaned up the places where I touched with linting warnings.
* Closes #1431

[#1431] Add capacity_building flag to resources

---

backend/src/gpml/handler/resource/translation.clj

* Read operations on approved resources is public. We don't
need to check if the user is approved. In this case, the user may be or
not there depending if it's logged in or not. That is why we get
unauthorized when calling the API with a user that is not logged in
or not approved.

Fix get translation endpoint permissions

---

backend/src/gpml/db/country-group.sql
backend/src/gpml/db/landing.clj
backend/src/gpml/handler/browse.clj
backend/src/gpml/handler/community.clj
backend/src/gpml/handler/landing.clj
backend/test/gpml/db/landing_test.clj
backend/test/gpml/db/topic_test.clj

* Browse API was handling the country groups and countries count wrong
because we were retrieving their values wrongly.
* Landing API was counting the transnationals wrong because it was
considering duplicate values.

Fix browse and landing API resource count bugs

---

backend/resources/gpml/config.edn
backend/src/gpml/db/landing.clj
backend/src/gpml/db/landing.sql
backend/src/gpml/db/stakeholder_association.sql
backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj
backend/src/gpml/handler/landing.clj
backend/test/gpml/db/landing_test.clj

Main issues:
* Improves performance. All counts in a single query.
* Fix country groups count. Counting using solely the
<resource>_geo_coverage table was not enough and more than often gave
wrong counts. This new query simplifies not only the map count but the
topic query itself because we don't need geo coverage CTE anymore. All
information needed to aggregate resource count per country and country
group is contained in the `geo_coverage_countries` and
`geo_coverage_country_groups` fields generated from the topic
query. This means 5 geo coverage queries less to process.
Secondary issues:
* Remove the limit from browse API.

Refactor landing API to simplify resource map count

---

backend/resources/gpml/config.edn
backend/resources/migrations/173-remove-is-bookmark-from-favorite-tables.up.sql
backend/src/gpml/db/favorite.sql
backend/src/gpml/db/resource/connection.sql
backend/src/gpml/db/topic.clj
backend/src/gpml/handler/favorite.clj
backend/test/gpml/db/favorite_test.clj
backend/test/gpml/handler/browse_test.clj
backend/test/gpml/handler/favorite_test.clj

* The endpoint was not create and deleting bookmarks properly.
* Ideally bookmarks, follow and association should be splited into
three different things. This will need a refactor in the future.
* Removed `is_bookmark` from the tables as it doesn't add any benefit
since the association `interested in` is already treated as the
bookmark/follow value.

Fix favorites post endpoint

---

backend/resources/gpml/config.edn
backend/src/gpml/auth.clj
backend/src/gpml/handler/project.clj
backend/test/gpml/handler/project_test.clj

* GET endpoints should return projects owned by the user.
* GET/PUT/DELETE/:id should allow the request if the user owns the
specified project. Otherwise return an unauthorized response.

Update project's GET/PUT/DELETE endpoints to restrict by user

---

backend/src/gpml/db/landing.sql
backend/src/gpml/db/topic.clj
backend/src/gpml/handler/detail.clj

* The transnational count and national counts weren't calculated because initiative's geo_coverage_type was a JSON instead of a plain string. So when doing the WHERE conditions for `transnational` or `national,sub-national` values it would fail and always account to 0.

Fix map count for initiatives

---

backend/src/gpml/db/initiative.sql

[Closes #1482]
Added missing properties when returning resource data for initiatives, as we have stored them in the DB, the same format we load them when getting all the data from GET `/api/initiative/{id}` endpoint.
We have removed problematic `funding` property as it is not working well, to load the raw `q35` property, that contains this information. In the future we will refactor the code to provide a better meaning for the props of Initiative resource type.

Add missing init. data in Get res. det. endpoint

---

backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj
backend/test/gpml/handler/browse_test.clj

* Also, move all parameter parsing to the opts schema. We should always use Malli directly for parameter coercion, error handling, etc.
* Closes #1485

[#1485] Add upcoming filter and refactor browse API opts schema

---

backend/src/gpml/db/stakeholder.sql
backend/src/gpml/handler/stakeholder.clj
backend/src/gpml/handler/tag.clj

Fixed the problems described in the issue.
Now as a side-note for FE, we take into account `limit` property sent by FE, but if neither `limit` or `page` params are provided, we use default values hardcoded in BE (limit = 5; page = 0).

1488 fix get suggested profiles endpoint

---

backend/resources/gpml/config.edn
backend/src/gpml/handler/stakeholder.clj
backend/test/gpml/handler/profile_test.clj

* This fixes the issue where non-member organisations wouldn't have a creator.
* The refactor also makes the profile create/update safer. Everything needs to be executed successfully otherwise the transaction fails and everything is rolled back.
* Closes #1487

[#1487] Refactor stakeholder profile creation and edition

---

backend/resources/gpml/config.edn
backend/src/gpml/handler/image.clj

[closes #1492]
Now we check if the loaded image from the DB has Base64 format before parsing it like that in order to send FE the image as bytes array. For this check, we need to ensure first the image content is not empty and then check if it is a valid Base64 image, removing the possibly added headers for the check (since we store the Base64 headers too in order to have the metadata there).
In case the image does not have Base64 format, we treat it as an URL if we can build a correct URL from there. In case we can, the image is downloaded from the URL, so we can serve it as a bytes array, providing its content-type info as well. Thus FE can expect the image data always coming in the same format. Otherwise we cannot infer the image's content type just from the URL and would be harder to …

Fix GET `/image/{image_type}/{id}` endpoint

---

backend/src/gpml/db/topic.clj

* Using jsonb_object_keys on an empty JSOB won't return anything. Since it does an implicit LATERAL JOIN it won't include the record with empty geo_coverage_type in the results. To fix it, we are executing a sub-query to get the results from jsonb_object_keys which will return null for empty geo_coverage_type cases. This is probably not the best solution but a temporary one. We'll soon refactor intiatives schema and simplify many things such as this column.

Fix initiative geo_coverage_type transformation in topic query

---

backend/src/gpml/handler/image.clj

[closes #1492]
We were not handling image URLs appropriately, so now we check first if we can build a URL out of the image got from DB, so we try to download the image in that case, as before. However, if we cannot make a URL we make sure we have a valid string before trying to parse the image as Base64 content.
Now we also do proper logging, as we were not doing much before and we were expecting the logger config in the wrong place as argument.
Now the fetch image function is also safer in case there is no `status` got from the result, before trying to do further checks with its value.

Fix URL handle in GET `/image/{image-type}/{id}`

---

backend/src/gpml/auth.clj
backend/src/gpml/handler/resource/permission.clj

* If the user doesn't verify the email our BE authentication code assign a false value to the `:user` key in the autentication details. That was causing a problem when checking for permissions as we do `seq` on the `:user` key's value. That would case an exception. So now instead of assigning a false value we assign an empty map.
* I also changed in what order the permissions are checked because if it's a read we don't have to check for the user as resources are publicly readable.

Fix permission check when user didn't verify the email

---

backend/src/gpml/handler/stakeholder.clj

* If a parameter has a default value we can't say it's optional because then the default value is not applied.

Fix list stakeholder get params default values

---

backend/resources/gpml/config.edn
backend/src/gpml/auth.clj
backend/src/gpml/handler/detail.clj
backend/src/gpml/handler/resource/permission.clj
backend/src/gpml/handler/stakeholder.clj

* Fix permissions check for stakeholder. Stakeholders should be able to see their own profiles and allow other approved stakeholders see it too.
* Fix affiliation management to allow conversion from/to private citizen to member/non-member org affiliations.

Fix stakeholder affiliation submission and read permissions

---

backend/src/gpml/handler/stakeholder.clj

TODO: we should move all the organisation logic from `/profile` to `/organisation` endpoint as they are independent flows now from FE POV.

[#1509] Add missing program param in org spec on sign up endpoint

---

backend/src/gpml/handler/browse.clj

* Probably while refactoring we mistakenly changed this filter's value.

Fix browse API transnational filter typo

---

backend/resources/migrations/181-update-geo-coverage-tables-check-constraint.up.sql

* We want to make each row pair (<resource_column>, country|country_group|country_state) unique.
* We are also dropping the old constraint to check for null values on those columns. BE already ensure there never will be nulls on country<_x> columns.
* We were only creating the unique index before for case_study and project, but now all resources have it.

Fix geo coverage MxN tables constraints

---

backend/resources/gpml/config.edn
backend/src/gpml/handler/contact.clj
backend/src/gpml/util/email.clj

[Re #1517]
Added new endpoint similar to the Subscribe one, but in this case we are sending contact form data.
We support only Cobsea contact form case (that is the only case for now), but we have the endpoint ready for other cases, as long as we provide some configuration about destination email address.
We have decided to make the `source` parameter mandatory, as it's a different case as with other endpoints, since this would be mainly used from Cobsea and better be explicit.

1517 - Add new Contact endpoint for Cobsea

---

backend/src/gpml/db/landing.sql
backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj
backend/src/gpml/handler/landing.clj
backend/test/gpml/db/landing_test.clj
backend/test/gpml/handler/browse_test.clj

* Changing the topic query logic affects the landing and browse API which needed to be refactored as well.
* Now we use the actual entity names instead of geo-coverage and transnational. API endpoint parameters still on pending as it requires FE intervention.
* See #1522
* Closes #1522

[#1522] Fix country filter on topic query

---

backend/src/gpml/domain/types.clj
backend/src/gpml/handler/review.clj

* They were using the wrong set of review statuses, as it differs from review_status enum values. Which are used for resources only.
* Closes #1531

[#1531] Fix review endpoints review status malli schema

---

backend/resources/migrations/184-add-case-study-to-resource-type-enum.up.sql
backend/src/gpml/handler/comment.clj
backend/src/gpml/handler/detail.clj

* Comment RESOURCE_TYPE enum was missing the case_study value.
* Detail API needs to remove all geo_coverage_* fields from the entity data before inserting into the db. Ideally we should use Malli to get the entity keys for each resource instead of doing it manually. This is a refactor candidate.

Fix Case Study update on detail API and comments fetching

---

backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj

[Re #1537]
* The `featured` order by parameter will order in DESC mode as PostgreSQL booleans are 0 and 1 at the of the day. This way we always get the featured resources first in the list. In order to avoid the list being chaotic, subsequent resources will be ordered by `created`. So, we at least keep some meaningful order of resources.

Add featured order by to browse API

---

backend/src/gpml/db/detail.sql
backend/src/gpml/db/landing.sql
backend/src/gpml/db/stakeholder_association.sql
backend/src/gpml/db/topic.clj
backend/src/gpml/db/topic.sql

[Re #1544]
* This filter would break the query if the topic is case_study. Since case study do not have the `sub_content_type` filter, we remove it from the tables' list if the `sub_content_type` filter is used.

Fix topic query when using sub_content_type filter

---

backend/src/gpml/db/case_study.sql

[Re #1543]
The DB query used to update the case studies with the migrated images was missing the actual `update table set` prefix before the dynamic HugSQL-related part. After this the API should also work for migrating images that were not stored previously in GCS.

1543 Fix files migration for case studies in API

---

backend/src/gpml/service/file.clj

[Re #1543]
We were not including the namespace that extends the GCSStorageClient protocol with the methods to get blob signed URL and delete blob-related functionality, that was preventing the reading of private image files from GCS. This was not reproduced locally, since there we load always all the namespaces, which is not the case with the Uberjar. So now we require the mentioned file as part of the File service, that is required already, fixing the issue.

1543 Fix access to get private file URLs

---

backend/src/gpml/handler/detail.clj
backend/src/gpml/service/file.clj
backend/test/gpml/handler/detail_test.clj

This PR addresses 3 issues during the image update process when updating a resource:
- Fix the logic to finish image replacement after the old image is successfully deleted: the logic was inverted so we would be rolling back the process if the old images were deleted ok.
- Stop trying to delete old images that did not exist when updating a resource to remove a given image. Now we check if there is an actual previous image to be deleted before trying to do so.
- Fix limbo image state when failing resource update process. Now we delete removed image references in the DB after the images have been removed from GCS. So next time the user can try to upload the images that were meant to be replaced, without seeing broken links.

1543 fix resource file updates

---

backend/src/gpml/handler/organisation.clj
backend/src/gpml/service/stakeholder.clj

[Re #1576]
We were not getting the result right from the roles assignment utility function, when we needed to create `resource-owner` role for created non-member organisation related to the stakeholder being created. Now we have fixed that.
Besides we also have removed a print of a exception catched, in a separated ns related to organisations.
Fix for #1576 issue.

1576 Fix stakeholder creation service

---

backend/src/gpml/db/stakeholder.sql
backend/src/gpml/handler/stakeholder.clj
backend/src/gpml/handler/stakeholder/expert.clj
backend/src/gpml/service/stakeholder.clj

[Re #1582]
Fixed query to get experts results needed to be able to detect an expert user needs to be converted to an approved user.
Besides, we have instrumented the code of update stakeholder-related function to unassign unapproved user role from the expert user in case it is detected as such, and be able to assign the approved user role in that case as well. The added functions have their rollbacks as well and we have also added one for the update stakeholder's final function, to have a consistent behaviour.
On the other hand the endpoint to accept invitations looks not to be in use and such this looks like the only entrypoint to fix, but we will check.
Now we are also catching better the exceptions, using Throwable class.
This issue is related to #1530 and #1543  refactors.

1582 Fix experts invitations related permissions handling

---

backend/src/gpml/db/tag.sql
backend/src/gpml/handler/stakeholder.clj
backend/src/gpml/handler/tag.clj
backend/src/gpml/service/permissions.clj

[Re #1588]
As explained in the issue, we want to avoid throwing duplicate tag errors and use the tags that exist when needed, making it transparent for the frontend. So in order to achieve that we avoid conflicts when we find duplicate tags during the creation process, returning the data of both newly created tags and the conflicting ones, making it transparent for the frontend.
Once we have tried to create all the tags, we try to fetch related rbac context to know if we need to create a new context or not, since we cannot just try to create it, as it would cause an SQL error that could abort any ongoing DB transaction.
Ideally the frontend should send the ids when we are dealing with existing tags and we should change the backend code to avoid trying to create already existing tags, but …

1588 Avoid duplicate tags errors, using existing tags

---

backend/resources/gpml/config.edn
backend/src/gpml/db/organisation_detail.clj
backend/src/gpml/db/organisation_detail.sql
backend/src/gpml/handler/organisation_detail.clj

* Some cosmetic changes:
*  Use the long-version of the integrant key names on the `organisation_detail.clj` handlers.
* Declare HugSQL functions in the `db/organisation_detail.clj`.
* Fixes:
* Add picture file details to org members.
* Add picture file's url to org members.
* Use GPML common configuration object for `get-members` handler.

1608 build img urls for get-members endpoint

---

backend/resources/gpml/config.edn
backend/resources/migrations/194-support-private-tags.up.sql
backend/src/gpml/db/tag.sql
backend/src/gpml/domain/tag.clj
backend/src/gpml/handler/tag.clj

This PR provides support for private tags in the following ways:
- Support creating tags for super admins with new `private` property (`api/tag` POST endpoint). By default current tags will have the value as `false` (so they are publicly available).
- Support for Updating tags with the new mentioned property, for super admins. Here we have made some corrections to the endpoint as well.
- Ability to get the new property and use it for filtering in the public `/api/tag` GET endpoint. Besides this property is provided in other endpoints out of the box.

1619 support private tags

---

backend/resources/gpml/config.edn
backend/src/gpml/boundary/adapter/chat/rocket_chat/core.clj
backend/src/gpml/boundary/port/chat.clj
backend/src/gpml/handler/chat.clj
backend/src/gpml/service/chat.clj
backend/src/gpml/util.clj
backend/src/gpml/util/email.clj

This PR contains:
- Addition of a the new API endpoint needed for GPML admins to add a user into requested Forum's private channel, notifying the final user about it.
- Modification of the API endpoint to request to join a Forum's private channel in order to include a link in the notification email, for the front-end to be able to send an automated API request to use the new endpoint mentioned in the first point above, once the GPML admin confirms the approval with a button click.

1625 allow admins approve chat private channel join requests

---

backend/src/gpml/db/organisation.clj
backend/src/gpml/db/organisation.sql
backend/src/gpml/domain/organisation.clj
backend/src/gpml/handler/organisation.clj
backend/src/gpml/handler/programmatic/files_migrator.clj
backend/src/gpml/service/stakeholder.clj

This PR contains:
- Fix of storing tags associations for a given organisation when it is being updated.
- Fix of logo update handling. Now we avoid deleting the current logo when we are not trying to update this info.

1629 Fix organisation update functionality (backend)

---

backend/src/gpml/util/email.clj

[Re #1625]
The originally provided link was wrong so now we have updated it according to the front-end needs.

1625 Update link to review forum private channel request

---

backend/src/gpml/db/resource/tag.sql

[Re #1619]
We have been requested to load the mentioned property among the tags data related to the target resource data obtained in the GET Resource Details-related endpoint.
As a side effect, we will also load it in other use-cases, but that is not harmful and it can be even better for the future.

1619 Provide `private` property of tags in GET Resource Detail endpoint

---

backend/src/gpml/db/organisation.clj
backend/src/gpml/db/organisation.sql
backend/src/gpml/db/resource/tag.sql
backend/src/gpml/handler/detail.clj
backend/src/gpml/handler/initiative.clj
backend/src/gpml/handler/organisation.clj
backend/src/gpml/handler/stakeholder.clj
backend/src/gpml/handler/stakeholder/tag.clj
backend/src/gpml/handler/submission.clj
backend/src/gpml/service/stakeholder.clj
backend/test/gpml/handler/profile_test.clj

[Re #1636]
As explained in the issue, we need to return all the tags related to the target organisation, for the endpoint mentioned above. Hence, we have removed the legacy DB query to use the generic one for the resource details get functionality. Obviously we no longer get tags grouped by category and we avoid the strange random get of the first group of tags, so we just return a collection with the ids of all the found tags.
In order to re-use the shared mentioned get resource tag's DB query, we have needed to modify it so we can optionally pass a filter to be used in the current places it was being used, so only approved tags were considered there, while we can use the query without filters for the use-case we are dealing with here.

1636 Fix expertise tags in `/api/organisation/{id}` GET endpoint

---

backend/src/gpml/handler/detail.clj
backend/src/gpml/handler/organisation.clj
backend/src/gpml/handler/resource/tag.clj

[Re #1638]
As described in the issue, now we check in the affected API endpoints whether we get the `tags` key at all in the payload, so we know if we need to remove all the tag relationships, add/remove some of them or we just ignore tags during the update (in case we do not receive such property at all).
We have needed to update the generic tag update code to allow this use-case.

1638 Fix emptying tags in resource/org edition

---

backend/src/gpml/handler/community.clj

* The modified-filters binding was overwritting the filters we get in the API. Thus, not respecting what search criteria and returning unexpected results.

Fix community API filters overwritting

---

backend/resources/gpml/config.edn
backend/resources/migrations/198-setup-plastic-strategy-files-model.up.sql
backend/src/gpml/db/plastic_strategy/file.clj
backend/src/gpml/db/plastic_strategy/file.sql
backend/src/gpml/handler/plastic_strategy/file.clj
backend/src/gpml/service/plastic_strategy/file.clj

* Plastic strategy files are organized per section. So we store a
"section_key" metadata so the FE knows exactly where the file belongs
to.
* As per internal decision the BE will not limit the amount of files
per section key. Therefore, each section can have as many files as necessary.
---
- https://app.asana.com/0/0/1205545816718928

1611 plastic strategy files management

---

backend/resources/migrations/199-add-section-key-to-ps-bookmark.up.sql
backend/src/gpml/db/plastic_strategy/bookmark.sql
backend/src/gpml/db/topic.clj
backend/src/gpml/handler/browse.clj
backend/src/gpml/handler/plastic_strategy/bookmark.clj
backend/src/gpml/service/plastic_strategy/bookmark.clj

* Bookmarks are organized by sections not globally just by plastic
strategy. A resource can be bookmark in multiple sections of a plastic
strategy.
* Initially the "section_key" is of text type as per internal decision
of making PS sections content opaque for the BE. So transforming it
into an enum would contradict that decision.

1611 add section keys to ps bookmark

---

backend/resources/gpml/config.edn
backend/src/gpml/db/organisation.clj
backend/src/gpml/db/organisation.sql
backend/src/gpml/handler/organisation.clj

[Re #1611]
As we needed to get Plastic Strategy Workflow feature-specific new information related to organisations, which includes advance sorting and filtering capabilities, we have decided to implement a new endpoint just for that, which will be also useful in the future for other use-cases.
The reason not to use Browse API for this was to avoid adding more complexity to that query, as in the past we removed organisations as resource type to be provided through Browse API, in order to keep performance and complexity in the right balance. On the other hand, community members related endpoint was mixing stakeholders with the organisations data and it would be a mess as well to re-use this endpoint for the Stakeholder Map view in PSW.
PSW Bookmarking related capabilities are yet to be …

1611 Add new endpoint for GET Organisations in Stakeholder Map step in Plastic Strategy Workflow

---

backend/src/gpml/db/organisation.clj
backend/src/gpml/db/organisation.sql
backend/src/gpml/handler/organisation.clj

See commit's [message](https://github.com/akvo/unep-gpml/commit/4ed0e829d1c6d668c581f4b1c74bdfc04466c2cd) for the details.
In this PR we are also fixing the counter result shape of the total amount of organisations loaded in the endpoint (that differs from the paginated result's content).

1611 support PS bookmarks in get organisations endpoint

---

backend/src/gpml/db/plastic_strategy/bookmark.clj
backend/src/gpml/service/plastic_strategy/bookmark.clj

[Re #1611]
* In cases where the entity type is "case_study" the "ps-bookmark-entity-col" splitting will produce a wrong "entity-name". So instead of doing all of this work of splitting the "ps-bookmark-entity-col" we can just pass the "entity-type" already available in our service layer.
---
- https://app.asana.com/0/0/1205545816718924

Fix PS bookmark entity-type parsing for constraint violation check

---

backend/src/gpml/db/topic.clj

[Re #1611]
* PS bookmark would be duplicated in some occurrences. This might be due to the query complexity of `LEFT JOIN`s generating multiple rows for a single entity even after grouping. For now this is a quick fix but we should take quality time to refactor this query to make it right.

Fix topic query PS bookmark duplicates

---

backend/src/gpml/handler/badge.clj

* This would prevent the usage of the badge ID and result in a 500 status could with no explanation about the error because the "result" would be always "nil" in case "badge-id-or-name" is an integer.
* Use a more idiomatic Malli schema for positive integers.

Remove string check on badge-id-or-name as it can be an integer too

---

backend/src/gpml/handler/badge.clj

* As explained in the code comment this is a bypass and should be removed in the future in favor of RBAC system check.

Except country-validated badge from RBAC check

---

backend/src/gpml/db/organisation.clj
backend/src/gpml/db/organisation.sql
backend/src/gpml/handler/organisation.clj

[Re #1611]
We need to include the same information we are adding in other APIs such as Submission one, in order to conditionally load Badges assignation-related metadata for the listed organisations.
So, now the endpoint allows a `badge` query param boolean value to be able to load badges-related metadata.

1611 Support badges-metadata in Organisations List endp.

---

frontend/src/modules/workspace/view.jsx

This problem occurs because using promise all requires all request statuses to be `fulfilled`, when one of them has an error the other requests will stop. For that, we need to replace `Promise.all` with `Promise.allSettled` to execute all requests to completion even if some fail.
---
- https://app.asana.com/0/0/1205646367469922

Forum: Fix forum section isn't fully loaded

---

backend/resources/gpml/config.edn
backend/src/gpml/handler/detail.clj

* Query parameters were being discarded because it was not defined for coercion.

Refactor and fix GET detail API parameters handling

---

backend/src/gpml/handler/detail.clj

* Detail API should always return "assigned_badges" by default.

Set badges by default in GET detail API

---

frontend/src/modules/forum/forum-iframe.jsx
frontend/src/pages/forum/[channelName].jsx
frontend/src/pages/forum/channel.module.scss

If the user attempts to take an action (Join a forum, request to join) then we show the Login modal. After login it should redirect to /forum so that we enable the forum for the user.

Forum: Channel details for non-logged-in user

---

backend/src/gpml/db/plastic_strategy/team.clj
backend/src/gpml/handler/plastic_strategy/team.clj
backend/src/gpml/service/plastic_strategy/team.clj

* Every user added to a plastic strategy needs to have a chat account enabled in order to add them to the PS channel. Therefore, I added an extra step to create a user account in RocketChat if it doesn't have one already. Since creating the "Forum" (i.e. RocketChat) account is completely transparent for the user using the platform, this is also something that only concerns the BE.
* Improved the error handling on the `add-ps-team-member` handler and service layer to return conflict if the team member already exists.

Create chat account on add ps team member if required

---

backend/src/gpml/db/organisation.clj

* Before the filter would match any of the tags passed as filters but we want to match all of them. So basically it's an AND instead of OR.

Fix organisations query to match all tags instead of any

---

backend/src/gpml/db/organisation.clj
backend/src/gpml/db/organisation.sql

endpoint
[Re #1611]
We need to filter the strengths count according to the provided PS iso code from the params, so only those bookmarked initiatives for the given PS are taking into account when the PS iso code is provided. In this case, we do not count again same bookmarks for different sections, as it is only relevant the PS used to bookmark those initiatives.
---
- https://app.asana.com/0/0/1205859571336278

1611 Support strengths prop filtering by PS code in Organisations GET endpoint

---

backend/src/gpml/handler/stakeholder.clj
backend/src/gpml/handler/stakeholder/expert.clj
backend/src/gpml/handler/stakeholder/tag.clj
backend/src/gpml/service/stakeholder.clj

[Re #1734]
As explained in the issue, the generic user (stakeholder) tag assignation machinery was not ready to allow to remove all the tags of a given relation-category (offering, seeking or expertise), so now we have refactored the code to allow so. Since, the tags assignation is a partial thing (per category), the fix is quite more ellaborated, as we need to keep the old tags that are not part of the target category, so those are not overriden.
---
- https://app.asana.com/0/0/1205913551594845

1734 Allow total tags removal from stakeholders

---

backend/dev/resources/test.edn
backend/dev/src/mocks/boundary/adapter/chat/rocket_chat.clj
backend/src/gpml/handler/submission.clj
backend/src/gpml/service/stakeholder.clj

* I'm moving the chat account creation from user approval to sign
up. So now, when the user finishes the onboarding process we create
its account on RocketChat.

Create chat account on GPML sign up

---

backend/resources/migrations/203-add-missing-on-delete-cascade-constraints.up.sql
backend/src/gpml/db/resource/detail.clj
backend/src/gpml/db/resource/detail.sql
backend/src/gpml/handler/detail.clj

* These tables needs to have the ON DELETE CASCADE constraint so
PostgreSQL handles the deletion of references by itself.
* Also use HugSQL available functions to delete the associated
references that can't have a foreign key, i.e., "rbac_context" and "related_content".
---
- https://app.asana.com/0/0/1205956160722172

Fix delete resource in detail api

---

backend/src/gpml/db/plastic_strategy.sql
backend/src/gpml/handler/plastic_strategy.clj

* If the "rbac-user-id" has the "plastic-strategy/read" permission then it can read that plastic strategy information. So, we filter out those PSes in which the user doesn't have permissions.
---
- https://app.asana.com/0/0/1205999789361874

Filter PSes based on RBAC user read permission

---

backend/src/gpml/db/landing.sql

* The idea here is to get those resources that have "geo_coverage_type" = "transnational", take their transnational values ("geo_coverage_country_groups") and retrieve the countries associated to each transnational. This way we link a transnational resource to all countries that are part of a specific transnational group. For example, if we have an Event resource which its "geo_coverage_type" is "transnational" and the value is "Europe", we should add +1 to the counter of all countries that are part of "Europe" country group.
* Before we were matching all possible values of "geo_coverage" by using the "geo_coverage_values" which has a mix of "geo_coverage_countries" and "geo_coverage_country_groups" which is not right. We just want to get the country groups of the resource and link it to …

Fix logic for transnational_counts_per_country CTE in map-counts

---

backend/project.clj
backend/resources/gpml/config.edn
ci/build-prod.sh
ci/deploy-prod.sh

* Update misc deps
* This helps us avoid misc warnings and CVEs.
* Ensure Sentry has an environment set
* Use `set -Eeuxo pipefail` in production builds/deployments

Upgrade misc deps

---

backend/src/gpml/db/resource/geo_coverage.sql

This had been around for a couple years, resulting in a Sentry-visible issue.

Fix a syntax error in .sql file

---

backend/.gitignore
backend/src/gpml/db/resource/tag.clj
backend/src/gpml/scheduler/brs_api_importer.clj
backend/src/gpml/scheduler/leap_api_policy_importer.clj

https://akvo-foundation.sentry.io/issues/5022209500 popped up this morning. It was an old latent bug.

Avoid sql error in `get-tags-from-resources`

---

.env
ci/k8s/deployment.template.yml

Also removes env vars no longer used following https://github.com/akvo/unep-gpml/pull/1807

Set `DEAD_SIMPLE_CHAT_API_KEY` in k8s

---

backend/src/gpml/util/http_client.clj

* Specify a `:connection-request-timeout`
* Log the http timeouts as adequate

HTTP client refinements

---

backend/dev/src/dev.clj
backend/resources/migrations/207-create_chat_channel_membership.up.sql
backend/resources/migrations/208-add_chat_channel_id_index.up.sql
backend/src/gpml/db.clj
backend/src/gpml/handler/chat.clj
backend/src/gpml/handler/detail.clj
backend/src/gpml/service/chat.clj
backend/src/gpml/service/plastic_strategy.clj
backend/src/gpml/service/plastic_strategy/team.clj
backend/src/gpml/service/stakeholder.clj
backend/src/gpml/util/thread_transactions.clj

Now joining a channel is performed primarily though the service, which takes care of DSC-level joning, and DB-level persistence.
Membership queries now hit our DB, not DSC.

Refactor chat channel joining

---

backend/resources/migrations/206-create-chat-channel-metadata.up.sql

Chaning migrations' contents alters their sha, foiling migrations application in production.

Undo a comment from a migration

---

backend/project.clj
backend/test-resources/gpml/test-ci.edn
backend/test/gpml/fixtures.clj

It's useful to use JSON logging in CI, since  the `timbre-json-appender` logger shows all the contexts (per `timbre/with-context+`).

Upgrade `timbre-json-appender`, use it in CI

---

backend/src/gpml/boundary/adapter/chat/ds_chat.clj
backend/src/gpml/boundary/port/chat.clj
backend/src/gpml/handler/chat.clj
backend/src/gpml/service/chat.clj

* Correctly destructure `unique-user-identifier`
* Remove `:chat-account-id` from a Swagger schema
* It's a property used internally and removed before being returned over HTTP.

Fixes mar 13

---

backend/src/gpml/boundary/port/chat.clj
backend/src/gpml/handler/main.clj

@martinchristov NOTE: org name is now optional in the related Chat endpoint, reflecting the DB schema.
Swagger was more strict than our DB in this case.

Make org name optional

---

backend/src/gpml/boundary/adapter/chat/ds_chat.clj
backend/src/gpml/boundary/port/chat.clj

`:privacy`, `:metadata`, `:description`.
Can be seen both when showing a single channel, or a list thereof.
cc @martinchristov

Return new attributes when presenting channels

---

backend/src/gpml/boundary/adapter/chat/ds_chat.clj
backend/src/gpml/service/chat.clj

This one really fixes it after the insufficient https://github.com/akvo/unep-gpml/pull/1856
It's tricky as internally, channels have to, simultaneously:
- include specified channels (per our DB)
- exclude channels that DSC considers as user-joined (even if there's no such concept for them, as far as public channels go)

Fix `/user/channel` endpoint to not return channels that the user left

---

backend/src/gpml/handler/chat.clj
backend/src/gpml/service/chat.clj

Idempotently ensures that the given user has a chat account.
[http://localhost:3000/api/docs/index.html#/chat/post_api_chat_admin_channel__id__add_user__user_id_](http://localhost:3000/api/docs/index.html#/chat/post_api_chat_admin_channel__id__add_user__user_id_)

Implement admin 'add user to channel' endpoint

---

backend/resources/gpml/duct.base.edn
backend/src/gpml/db/plastic_strategy.clj
backend/src/gpml/handler/browse.clj
backend/src/gpml/handler/chat.clj
backend/src/gpml/handler/organisation.clj
backend/src/gpml/handler/plastic_strategy.clj
backend/src/gpml/handler/plastic_strategy/bookmark.clj
backend/src/gpml/handler/plastic_strategy/file.clj
backend/src/gpml/handler/plastic_strategy/team.clj
backend/src/gpml/handler/programmatic/plastic_strategy.clj
backend/src/gpml/service/plastic_strategy.clj
backend/src/gpml/service/plastic_strategy/team.clj
backend/src/gpml/service/stakeholder.clj

Ensures that the given plastic strategy has an existing, valid associated chat channel. Idempotent. Admin only.
We may create similar endpoints for similar needs (e.g. ensuring that users have an existing DSC account or an in-sync profile picture)
Swagger:

Implement Plastic Stragegy `/ensure-chat` endpoint

---

backend/src/gpml/db/plastic_strategy/team.clj
backend/src/gpml/service/plastic_strategy.clj
backend/src/gpml/service/plastic_strategy/team.clj

As (unfortunately) usual, exceptions were being swalloed in misc corners of the codebase, making diagnostics unnecessarily  hard.
@martinchristov , please reproduce the `There is a 500 when trying POST /api/plastic-strategy/0A/team/member` issue. It should fail again, just with better logs.
Please record the exact time of your attempt
Cheers - V

Make `plastic-strategy` code fail more clearly

---

backend/dev/src/dev.clj
backend/resources/gpml/duct.base.edn
backend/seeder/gpml/seeder/dummy.clj
backend/seeder/gpml/seeder/main.clj
backend/src/gpml/boundary/adapter/chat/ds_chat.clj
backend/src/gpml/main.clj
backend/src/gpml/service/permissions.clj
backend/test/gpml/fixtures.clj

Now, channel listings are limited to production/test/local - i.e. results won't be mixed any more.
Creating channels marks them as belonging them to production/test/local.
Existing test channels have already been marked as such.

DSC chat: introduce environment profiles

---

backend/resources/migrations/213-fix-stakeholder-badge-stakeholder-id-fkey.up.sql

It was missing an `ON DELETE CASCADE`

Fix `stakeholder_badge_stakeholder_id_fkey` constraint

---

backend/src/gpml/handler/chat.clj
backend/src/gpml/service/chat.clj

Affected endpoints:
* /api/chat/channel/all
* /api/chat/channel/public
* /api/chat/channel/private
* /api/chat/user/channel

Chat listings: filter out Plastic Strategy channels from results

---

backend/src/gpml/handler/chat.clj
backend/src/gpml/timbre_logger/json.clj
backend/src/gpml/util/http_client.clj

* Allow `:reason` to be returned in remaining Chat endpoints
* Fix HTTP JSON context logging

Fix HTTP JSON context logging

---

backend/.cljfmt.edn
backend/dev/src/dev.clj
backend/src/gpml/boundary/adapter/chat/ds_chat.clj
backend/src/gpml/scheduler/chat_message_summarizer.clj
backend/src/gpml/service/chat.clj

* Don't hit the DSC /messages endpoint with a limit of just `1`
* Avoid `reduce` when possible - can act funny
* More precise logging

`chat-message-summarizer`: misc refinements

---

backend/resources/gpml/duct.base.edn
backend/src/duct_hierarchy.edn
backend/src/gpml/boundary/adapter/chat/ds_chat.clj
backend/src/gpml/boundary/port/chat.clj
backend/src/gpml/db/stakeholder.sql
backend/src/gpml/scheduler/picture_file_reconciler.clj

Ensures that for any given Stakeholder record,
its corresponding DSC account has the same profile picture.
This serves two purposes:
- Fix all the profile pictures that were initially missing in DSC.
- (this purpose will become outdated after the first successful run)
- Propagate any possible profile picture changes from our app to DSC.
- It's a quite infrequent case, so this job is safe to run infrequently as well.

Introduce `gpml.scheduler.picture-file-reconciler`

---

backend/src/gpml/db/topic.clj

When aggregating the json objects into an array, the query makes a cartesian product of files x tags, duplicating the same file per number of tags.

Fix duplicated records under `files` property

---

nginx/templates/default.conf.template

https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ignore_headers
We want to cache resized images as much as possible

Feature: Ignore GCS cache headers

---

nginx/Dockerfile
nginx/templates/default.conf.template

- The default value for inactive keys is 10min. We want to keep the files as long as possible.
- Remove misleading comments. It seems that proxy_cache_valid does not support all possible time settings.

Feat: Fix cache inactive keys invalidation

---

ci/k8s/deployment.template.yml

The `nginx` container is prepared to use an environment variable, we use the same config from Strapi

Fix: Use the GCS_BUCKET_URL from Strapi config

---

backend/src/gpml/handler/detail.clj

Fix `GET /api/detail/project/{id}` returns empty response

Fix GET /api/detail/project/{id}

---

frontend/src/modules/flexible-forms/form.jsx
frontend/src/pages/add-content/index.jsx

Transform Case Study form to use description field instead of summary to match database schema. This resolves the 'column summary does not exist' error when updating Case Studies.
Changes:
- Update Case Study form submission to transform summary → description field
- Change Case Study form configuration to use description field
- Add Case Study editing logic to handle field transformation between frontend and backend
---
- https://app.asana.com/0/0/1210341594674167

Fix Case Study field mismatch error
